export interface CaseSkin {
  name: string;
  rarity: 'mil-spec' | 'restricted' | 'classified' | 'covert' | 'special';
  weapon: string;
}

export interface CaseData {
  id: string;
  name: string;
  year: number;
  releaseDate: string;
  keyPrice: number;
  casePrice?: number;
  type: 'weapon' | 'souvenir' | 'collection';
  description: string;
  image: string;
  knife: string;
  skins: CaseSkin[];
}

// Steam CDN image helper — uses the weapon + skin name to build a placeholder
// In production these would be real Steam CDN URLs
export function getSkinImageUrl(weapon: string, skinName: string): string {
  // Encode for URL safety
  const slug = `${weapon}-${skinName}`.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return `/images/skins/${slug}.png`;
}

// Reverse lookup: find which case(s) contain a given skin by weapon + name
export function getCasesForSkin(weapon: string, skinName: string): CaseData[] {
  const results: CaseData[] = [];
  for (const caseData of Object.values(caseDatabase)) {
    if (caseData.skins.some(s => s.weapon === weapon && s.name === skinName)) {
      results.push(caseData);
    }
  }
  return results;
}

export const caseDatabase: Record<string, CaseData> = {
  'kilowatt': {
    id: 'kilowatt',
    name: 'Kilowatt Case',
    year: 2024,
    releaseDate: 'February 2024',
    keyPrice: 2.50,
    type: 'weapon',
    description: 'First weapon case introduced to CS2 with orange container design.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFQznaKdID5D6d23ldHSwKOmZeyEz21XvZZ12LzE9t6nigbgqkplNjihJIaLMlhpF1ZeR5c',
    knife: 'Kukri Knife',
    skins: [
      { name: 'Chrome Cannon', rarity: 'covert', weapon: 'AWP' },
      { name: 'Inheritance', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Black Lotus', rarity: 'classified', weapon: 'M4A1-S' },
      { name: 'Jawbreaker', rarity: 'classified', weapon: 'USP-S' },
      { name: 'Olympus', rarity: 'classified', weapon: 'Zeus x27' },
      { name: 'Etch Lord', rarity: 'restricted', weapon: 'M4A4' },
      { name: 'Just Smile', rarity: 'restricted', weapon: 'MP7' },
      { name: 'Block-18', rarity: 'restricted', weapon: 'Glock-18' },
      { name: 'Hybrid', rarity: 'restricted', weapon: 'Five-SeveN' },
      { name: 'Analog Input', rarity: 'restricted', weapon: 'Sawed-Off' },
      { name: 'Hideout', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Dark Sigil', rarity: 'mil-spec', weapon: 'Nova' },
      { name: 'Irezumi', rarity: 'mil-spec', weapon: 'XM1014' },
      { name: 'Light Box', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Dezastre', rarity: 'mil-spec', weapon: 'SSG 08' },
      { name: 'Slag', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Motorized', rarity: 'mil-spec', weapon: 'UMP-45' },
    ],
  },
  'gallery': {
    id: 'gallery',
    name: 'Gallery Case',
    year: 2024,
    releaseDate: 'October 2024',
    keyPrice: 2.35,
    type: 'weapon',
    description: 'Armory-exclusive case featuring community-designed skins with a Kukri Knife in Chroma finish.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFQ0naTKJjhHu92ywoSIlq_3Zu7Vxm0CuMFwi-2Wpojw0APnqBBuYW31JY6LMlhpMMztXwM',
    knife: 'Kukri Knife (Chroma)',
    skins: [
      { name: 'Vaporwave', rarity: 'covert', weapon: 'M4A1-S' },
      { name: 'Gold Toof', rarity: 'covert', weapon: 'Glock-18' },
      { name: 'Epicenter', rarity: 'classified', weapon: 'P250' },
      { name: 'Neo-Noir', rarity: 'classified', weapon: 'UMP-45' },
      { name: 'The Outsiders', rarity: 'classified', weapon: 'AK-47' },
      { name: 'Rapid Transit', rarity: 'restricted', weapon: 'SSG 08' },
      { name: 'Randy Rush', rarity: 'restricted', weapon: 'P90' },
      { name: 'Saiba Oni', rarity: 'restricted', weapon: 'MAC-10' },
      { name: 'Turbine', rarity: 'restricted', weapon: 'M4A4' },
      { name: 'Hydro Strike', rarity: 'restricted', weapon: 'Dual Berettas' },
      { name: 'Calligraffiti', rarity: 'mil-spec', weapon: 'Desert Eagle' },
      { name: 'Tango', rarity: 'mil-spec', weapon: 'R8 Revolver' },
      { name: '27', rarity: 'mil-spec', weapon: 'USP-S' },
      { name: 'Trail Blazer', rarity: 'mil-spec', weapon: 'SCAR-20' },
      { name: 'Statics', rarity: 'mil-spec', weapon: 'MP5-SD' },
      { name: 'Hypnosis', rarity: 'mil-spec', weapon: 'M249' },
      { name: 'Drop Me', rarity: 'mil-spec', weapon: 'Negev' },
    ],
  },
  'revolution': {
    id: 'revolution',
    name: 'Revolution Case',
    year: 2023,
    releaseDate: 'February 2023',
    keyPrice: 2.30,
    type: 'weapon',
    description: 'Features cutting-edge weapon finishes and industrial aesthetics.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFQynaHMJT9B74-ywtjYxfOmMe_Vx28AucQj3brAoYrz3Fay_kY4MG_wdYeLMlhpLMaM-1U',
    knife: 'Kukri Knife',
    skins: [
      { name: 'Cyber Security', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Vent Rush', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Immovable Force', rarity: 'classified', weapon: 'AWP' },
      { name: 'Crazy 8', rarity: 'classified', weapon: 'R8 Revolver' },
      { name: 'Toy Box', rarity: 'classified', weapon: 'UMP-45' },
      { name: 'Revolt', rarity: 'restricted', weapon: 'P250' },
      { name: 'Insomnia', rarity: 'restricted', weapon: 'Glock-18' },
      { name: 'Sakkaku', rarity: 'restricted', weapon: 'M4A1-S' },
      { name: 'Dark Filigree', rarity: 'restricted', weapon: 'SG 553' },
      { name: 'Alien Pulse', rarity: 'restricted', weapon: 'FAMAS' },
      { name: 'Colony IV', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Twine', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Spring Loaded', rarity: 'mil-spec', weapon: 'MP5-SD' },
      { name: 'CaliCamo', rarity: 'mil-spec', weapon: 'P90' },
      { name: 'R8 Memento', rarity: 'mil-spec', weapon: 'SCAR-20' },
      { name: 'Yellow Jacket', rarity: 'mil-spec', weapon: 'MP9' },
      { name: 'The Executioner', rarity: 'mil-spec', weapon: 'MAG-7' },
    ],
  },
  'recoil': {
    id: 'recoil',
    name: 'Recoil Case',
    year: 2022,
    releaseDate: 'July 2022',
    keyPrice: 2.20,
    type: 'weapon',
    description: 'Features the USP-S Printstream and AWP Chromatic Aberration as coverts, with Broken Fang Gloves as rare specials.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFQxnaecIT8Wv9rilYTYkfTyNuiFwmhUvpZz3-2Z9oqg0Vew80NvZzuiJdeLMlhpwFO-XdA',
    knife: 'Broken Fang Gloves',
    skins: [
      { name: 'Printstream', rarity: 'covert', weapon: 'USP-S' },
      { name: 'Chromatic Aberration', rarity: 'covert', weapon: 'AWP' },
      { name: 'Ice Coaled', rarity: 'classified', weapon: 'AK-47' },
      { name: 'Visions', rarity: 'classified', weapon: 'P250' },
      { name: 'Devourer', rarity: 'classified', weapon: 'Sawed-Off' },
      { name: 'Crazy 8', rarity: 'restricted', weapon: 'R8 Revolver' },
      { name: 'Dragon Tech', rarity: 'restricted', weapon: 'SG 553' },
      { name: 'Ropz Agent', rarity: 'restricted', weapon: 'P90' },
      { name: 'Hazard Pay', rarity: 'restricted', weapon: 'UMP-45' },
      { name: 'Agua De Coco', rarity: 'restricted', weapon: 'Five-SeveN' },
      { name: 'Destroyer', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Oxide Blaze', rarity: 'mil-spec', weapon: 'M4A1-S' },
      { name: 'Banana Cannon', rarity: 'mil-spec', weapon: 'Desert Eagle' },
      { name: 'Disco Tech', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Plastic Flam', rarity: 'mil-spec', weapon: 'Negev' },
      { name: 'Rebel Cowl', rarity: 'mil-spec', weapon: 'SG 553' },
      { name: 'Fubar', rarity: 'mil-spec', weapon: 'PP-Bizon' },
    ],
  },
  'dreams-nightmares': {
    id: 'dreams-nightmares',
    name: 'Dreams & Nightmares Case',
    year: 2022,
    releaseDate: 'January 2022',
    keyPrice: 2.10,
    type: 'weapon',
    description: 'Community-designed case with 17 skins selected from 15,000+ submissions, each creator earning $100K.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFQwnfCcJmxDv9rhwIHZwqP3a-uGwz9Xv8F0j-qQrI3xiVLkrxVuZW-mJoWLMlhpWhFkc9M',
    knife: 'Butterfly/Bowie/Falchion/Huntsman/Shadow Daggers',
    skins: [
      { name: 'Nightwish', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Starlight Protector', rarity: 'covert', weapon: 'MP9' },
      { name: 'Abyssal Apparition', rarity: 'classified', weapon: 'MP7' },
      { name: 'Rapid Eye Movement', rarity: 'classified', weapon: 'FAMAS' },
      { name: 'Melondrama', rarity: 'classified', weapon: 'Dual Berettas' },
      { name: 'Night Terror', rarity: 'restricted', weapon: 'M4A1-S' },
      { name: 'Ticket to Hell', rarity: 'restricted', weapon: 'USP-S' },
      { name: 'Zombie Offensive', rarity: 'restricted', weapon: 'XM1014' },
      { name: 'Space Cat', rarity: 'restricted', weapon: 'PP-Bizon' },
      { name: 'Dream Glade', rarity: 'restricted', weapon: 'G3SG1' },
      { name: 'Scrawl', rarity: 'mil-spec', weapon: 'Five-SeveN' },
      { name: 'Poultrygeist', rarity: 'mil-spec', weapon: 'SCAR-20' },
      { name: 'Ensnared', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Spirit Board', rarity: 'mil-spec', weapon: 'Sawed-Off' },
      { name: 'Necro Jr.', rarity: 'mil-spec', weapon: 'MP5-SD' },
      { name: 'Lifted Spirits', rarity: 'mil-spec', weapon: 'P2000' },
      { name: 'Doodle Lore', rarity: 'mil-spec', weapon: 'Galil AR' },
    ],
  },
  'snakebite': {
    id: 'snakebite',
    name: 'Snakebite Case',
    year: 2021,
    releaseDate: 'May 2021',
    keyPrice: 2.00,
    type: 'weapon',
    description: 'Features snake-themed skins with Sport, Driver, and Hand Wrap Gloves as rare specials.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFU4naLOJzgUuYqyzIaIxa6jMOLXxGkHvcMjibmU99Sg3Qaw-hA_ZWrzLISLMlhpgJJUhGE',
    knife: 'Sport/Driver/Hand Wrap Gloves',
    skins: [
      { name: 'Printstream', rarity: 'covert', weapon: 'Desert Eagle' },
      { name: 'Fuel Injector', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Lapis Gator', rarity: 'classified', weapon: 'USP-S' },
      { name: 'Xiangliu', rarity: 'classified', weapon: 'Glock-18' },
      { name: 'Mister Fierce', rarity: 'classified', weapon: 'XM1014' },
      { name: 'Serpent Farewell', rarity: 'restricted', weapon: 'AK-47' },
      { name: 'Eco', rarity: 'restricted', weapon: 'M4A1-S' },
      { name: 'Djinn', rarity: 'restricted', weapon: 'Galil AR' },
      { name: 'Emerald Poison Dart', rarity: 'restricted', weapon: 'R8 Revolver' },
      { name: 'Abyss', rarity: 'restricted', weapon: 'Negev' },
      { name: 'Frog Camo', rarity: 'mil-spec', weapon: 'CZ75-Auto' },
      { name: 'Kami', rarity: 'mil-spec', weapon: 'SG 553' },
      { name: 'Mambinha', rarity: 'mil-spec', weapon: 'Nova' },
      { name: 'Sandstorm', rarity: 'mil-spec', weapon: 'P250' },
      { name: 'Motor Glitch', rarity: 'mil-spec', weapon: 'MP9' },
      { name: 'De Ansen', rarity: 'mil-spec', weapon: 'SCAR-20' },
      { name: 'Hacksaw', rarity: 'mil-spec', weapon: 'Sawed-Off' },
    ],
  },
  'fracture': {
    id: 'fracture',
    name: 'Fracture Case',
    year: 2020,
    releaseDate: 'August 2020',
    keyPrice: 1.90,
    type: 'weapon',
    description: 'Shattered glass and fractured aesthetics with Shattered Web Knives.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFU2nfGaJG0btN2wwYHfxa-hY-uFxj4Dv50nj7uXpI7w3AewrhBpMWH6d9CLMlhpEbAe-Zk',
    knife: 'Shattered Web Knives',
    skins: [
      { name: 'Printstream', rarity: 'covert', weapon: 'Glock-18' },
      { name: 'Fade', rarity: 'covert', weapon: 'Desert Eagle' },
      { name: 'Whiteout', rarity: 'classified', weapon: 'M4A4' },
      { name: 'Player Two', rarity: 'classified', weapon: 'P250' },
      { name: 'Paradigm', rarity: 'classified', weapon: 'Galil AR' },
      { name: 'Torn', rarity: 'restricted', weapon: 'AK-47' },
      { name: 'Shattered', rarity: 'restricted', weapon: 'MAG-7' },
      { name: 'Containment Breach', rarity: 'restricted', weapon: 'P90' },
      { name: 'Anomaly', rarity: 'restricted', weapon: 'SSG 08' },
      { name: 'Origami', rarity: 'restricted', weapon: 'Tec-9' },
      { name: 'Commuter', rarity: 'mil-spec', weapon: 'PP-Bizon' },
      { name: 'Impact Drill', rarity: 'mil-spec', weapon: 'SG 553' },
      { name: 'Short Circuit', rarity: 'mil-spec', weapon: 'P2000' },
      { name: 'Decimator', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Forbidden', rarity: 'mil-spec', weapon: 'M249' },
      { name: 'Night Borre', rarity: 'mil-spec', weapon: 'XM1014' },
      { name: 'Parabellum', rarity: 'mil-spec', weapon: 'Negev' },
    ],
  },
  'prisma2': {
    id: 'prisma2',
    name: 'Prisma 2 Case',
    year: 2020,
    releaseDate: 'April 2020',
    keyPrice: 1.80,
    type: 'weapon',
    description: 'Second Prisma case with iridescent light refraction effects and Horizon Knives.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFU1nfbOIj8W7oWzkYLdlPOsMOmIk2kGscAj2erE99Sn2AGw_0M4NW2hIYOLMlhpcmY0CRM',
    knife: 'Horizon Knives',
    skins: [
      { name: 'Phantom Disruptor', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Player Two', rarity: 'covert', weapon: 'M4A1-S' },
      { name: 'Vermillion Cloak', rarity: 'classified', weapon: 'MAG-7' },
      { name: 'Slate', rarity: 'classified', weapon: 'AWP' },
      { name: 'Wicked Sick', rarity: 'classified', weapon: 'Desert Eagle' },
      { name: 'Acid Fade', rarity: 'restricted', weapon: 'Glock-18' },
      { name: 'Mecha Industries', rarity: 'restricted', weapon: 'SG 553' },
      { name: 'Retribution', rarity: 'restricted', weapon: 'FAMAS' },
      { name: 'Grip', rarity: 'restricted', weapon: 'SSG 08' },
      { name: 'Eviction', rarity: 'restricted', weapon: 'Sawed-Off' },
      { name: 'Full Stop', rarity: 'mil-spec', weapon: 'P250' },
      { name: 'Animus', rarity: 'mil-spec', weapon: 'R8 Revolver' },
      { name: 'Tiger Moth', rarity: 'mil-spec', weapon: 'CZ75-Auto' },
      { name: 'Sky Stalker', rarity: 'mil-spec', weapon: 'SG 553' },
      { name: 'Afterimage', rarity: 'mil-spec', weapon: 'SCAR-20' },
      { name: 'Facility', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Off World', rarity: 'mil-spec', weapon: 'Nova' },
    ],
  },
  'prisma': {
    id: 'prisma',
    name: 'Prisma Case',
    year: 2019,
    releaseDate: 'March 2019',
    keyPrice: 1.70,
    type: 'weapon',
    description: 'Original Prisma case with rainbow refraction themes and Horizon Knives.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFUynfWaI25G6Ijkl9iPw_SnNrjXw2oBu8cj3b2Qo4_33QbnrUdlYD37ddCLMlhpvs0XIz0',
    knife: 'Horizon Knives',
    skins: [
      { name: 'The Emperor', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Neon Rider', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Neo-Noir', rarity: 'classified', weapon: 'AWP' },
      { name: 'Mechano', rarity: 'classified', weapon: 'Desert Eagle' },
      { name: 'Off World', rarity: 'classified', weapon: 'Five-SeveN' },
      { name: 'Moonrise', rarity: 'restricted', weapon: 'R8 Revolver' },
      { name: 'Phantom', rarity: 'restricted', weapon: 'USP-S' },
      { name: 'Crimson Tsunami', rarity: 'restricted', weapon: 'AUG' },
      { name: 'Static', rarity: 'restricted', weapon: 'XM1014' },
      { name: 'Trajectory', rarity: 'restricted', weapon: 'P250' },
      { name: 'Facility Draft', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Capillary', rarity: 'mil-spec', weapon: 'MP5-SD' },
      { name: 'Emerald Jormungandr', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Orange Peel', rarity: 'mil-spec', weapon: 'P90' },
      { name: 'Blueprint', rarity: 'mil-spec', weapon: 'FAMAS' },
      { name: 'Jungle Storm', rarity: 'mil-spec', weapon: 'MP7' },
      { name: 'Converter', rarity: 'mil-spec', weapon: 'MAG-7' },
    ],
  },
  'clutch': {
    id: 'clutch',
    name: 'Clutch Case',
    year: 2018,
    releaseDate: 'February 2018',
    keyPrice: 1.60,
    type: 'weapon',
    description: 'Features the first-ever gloves available in a regular weapon case.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFY5naqQIz4R7Yjix9bZkvKiZrmAzzlTu5AoibiT8d_x21Wy8hY_MWz1doSLMlhpM3FKbNs',
    knife: 'Specialist/Sport/Moto/Hydra Gloves',
    skins: [
      { name: 'Neo-Noir', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Neon Rider', rarity: 'covert', weapon: 'USP-S' },
      { name: 'Asiimov', rarity: 'classified', weapon: 'AUG' },
      { name: 'Fuel Injector', rarity: 'classified', weapon: 'Glock-18' },
      { name: 'Bloodsport', rarity: 'classified', weapon: 'MAG-7' },
      { name: 'Grip', rarity: 'restricted', weapon: 'AWP' },
      { name: 'Shattered', rarity: 'restricted', weapon: 'MP7' },
      { name: 'Carnivore', rarity: 'restricted', weapon: 'Nova' },
      { name: 'Triqua', rarity: 'restricted', weapon: 'XM1014' },
      { name: 'Mosaico', rarity: 'restricted', weapon: 'R8 Revolver' },
      { name: 'Spitfire', rarity: 'mil-spec', weapon: 'Negev' },
      { name: 'Survivor Z', rarity: 'mil-spec', weapon: 'SG 553' },
      { name: 'Scaffold', rarity: 'mil-spec', weapon: 'PP-Bizon' },
      { name: 'Crimson Tide', rarity: 'mil-spec', weapon: 'P2000' },
      { name: 'Urban DDPAT', rarity: 'mil-spec', weapon: 'UMP-45' },
      { name: 'Handgun', rarity: 'mil-spec', weapon: 'Desert Eagle' },
      { name: 'Brief', rarity: 'mil-spec', weapon: 'MP9' },
    ],
  },
  'spectrum2': {
    id: 'spectrum2',
    name: 'Spectrum 2 Case',
    year: 2017,
    releaseDate: 'September 2017',
    keyPrice: 1.50,
    type: 'weapon',
    description: 'Second spectrum case with vibrant color finishes and Spectrum Knives.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFY4naeaJGhGtdnmx4Tek_bwY-iFlGlUsJMp3LuTot-mjFGxqUttZ2r3d4eLMlhpnZPxZK0',
    knife: 'Spectrum Knives',
    skins: [
      { name: 'Empress', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Bloodsport', rarity: 'covert', weapon: 'Desert Eagle' },
      { name: 'Decimator', rarity: 'classified', weapon: 'M4A1-S' },
      { name: 'Aerial', rarity: 'classified', weapon: 'AUG' },
      { name: 'Rust Coat', rarity: 'classified', weapon: 'AWP' },
      { name: 'Retribution', rarity: 'restricted', weapon: 'CZ75-Auto' },
      { name: 'Mecha Industries', rarity: 'restricted', weapon: 'P250' },
      { name: 'Neo-Noir', rarity: 'restricted', weapon: 'PP-Bizon' },
      { name: 'Shattered', rarity: 'restricted', weapon: 'R8 Revolver' },
      { name: 'Oxide Blaze', rarity: 'restricted', weapon: 'XM1014' },
      { name: 'Slumber', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Dark Filigree', rarity: 'mil-spec', weapon: 'SSG 08' },
      { name: 'Amber Slipstream', rarity: 'mil-spec', weapon: 'P90' },
      { name: 'Copperhead', rarity: 'mil-spec', weapon: 'Glock-18' },
      { name: 'Turbo Peek', rarity: 'mil-spec', weapon: 'MP7' },
      { name: 'Inner Child', rarity: 'mil-spec', weapon: 'SG 553' },
      { name: 'Akoben', rarity: 'mil-spec', weapon: 'UMP-45' },
    ],
  },
  'danger-zone': {
    id: 'danger-zone',
    name: 'Danger Zone Case',
    year: 2018,
    releaseDate: 'December 2018',
    keyPrice: 1.55,
    type: 'weapon',
    description: 'Released alongside the Danger Zone battle royale mode.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFUxnaPLJz5H74y1xtTcz6etNumIx29U6Zd3j7yQoYih3lG1-UJqY27xJIeLMlhpaD9Aclo',
    knife: 'Horizon Knives',
    skins: [
      { name: 'Neo-Noir', rarity: 'covert', weapon: 'AWP' },
      { name: 'Asiimov', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Mecha Industries', rarity: 'classified', weapon: 'M4A4' },
      { name: 'Moonrise', rarity: 'classified', weapon: 'Glock-18' },
      { name: 'Neo-Noir', rarity: 'classified', weapon: 'USP-S' },
      { name: 'Trajectory', rarity: 'restricted', weapon: 'Desert Eagle' },
      { name: 'Darkwing', rarity: 'restricted', weapon: 'SSG 08' },
      { name: 'Vent Rush', rarity: 'restricted', weapon: 'MP9' },
      { name: 'Crimson Tsunami', rarity: 'restricted', weapon: 'MAC-10' },
      { name: 'Oxide Blaze', rarity: 'restricted', weapon: 'Galil AR' },
      { name: 'Scaffold', rarity: 'mil-spec', weapon: 'SG 553' },
      { name: 'Commuter', rarity: 'mil-spec', weapon: 'MP5-SD' },
      { name: 'Acid Etched', rarity: 'mil-spec', weapon: 'Nova' },
      { name: 'Neon Kimono', rarity: 'mil-spec', weapon: 'P250' },
      { name: 'Retrobution', rarity: 'mil-spec', weapon: 'Sawed-Off' },
      { name: 'Fubar', rarity: 'mil-spec', weapon: 'M249' },
      { name: 'Flash Forward', rarity: 'mil-spec', weapon: 'Tec-9' },
    ],
  },
  'cs20': {
    id: 'cs20',
    name: 'CS20 Case',
    year: 2019,
    releaseDate: 'October 2019',
    keyPrice: 1.65,
    type: 'weapon',
    description: 'Released to celebrate Counter-Strike\'s 20th anniversary.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFU0naHKIj9D7oTgl4LelaGnMuqIwDgFusR337HCpYmhiwzm8ktqMjv2INKLMlhprbp6CTE',
    knife: 'Classic Knife',
    skins: [
      { name: 'Wildfire', rarity: 'covert', weapon: 'AWP' },
      { name: 'Tatter', rarity: 'covert', weapon: 'FAMAS' },
      { name: 'Sacrificed', rarity: 'classified', weapon: 'MP9' },
      { name: 'Embargo', rarity: 'classified', weapon: 'P250' },
      { name: 'Classic Crate', rarity: 'classified', weapon: 'Five-SeveN' },
      { name: 'Acid Wash', rarity: 'restricted', weapon: 'AK-47' },
      { name: 'Flashback', rarity: 'restricted', weapon: 'AUG' },
      { name: 'Blueprint', rarity: 'restricted', weapon: 'UMP-45' },
      { name: 'Amnesia', rarity: 'restricted', weapon: 'MP5-SD' },
      { name: 'Desolate Space', rarity: 'restricted', weapon: 'Tec-9' },
      { name: 'Buckshot', rarity: 'mil-spec', weapon: 'MAG-7' },
      { name: 'Blueprint', rarity: 'mil-spec', weapon: 'SG 553' },
      { name: 'Stinger', rarity: 'mil-spec', weapon: 'P90' },
      { name: 'Death Grip', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Night', rarity: 'mil-spec', weapon: 'Sawed-Off' },
      { name: 'Jungle Slipstream', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Slate', rarity: 'mil-spec', weapon: 'Glock-18' },
    ],
  },
  'operation-bravo': {
    id: 'operation-bravo',
    name: 'Operation Bravo Case',
    year: 2013,
    releaseDate: 'September 2013',
    keyPrice: 2.50,
    type: 'weapon',
    description: 'Classic case featuring the legendary AK-47 Fire Serpent.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsXE1xNwVDv7WrFA5pnabNJGwSuN3gxtnawKOlMO6HzzhQucAm0uvFo4n2iw3h_UM-ZmilJNeLMlhpjfjxEoE',
    knife: 'Original Knives',
    skins: [
      { name: 'Fire Serpent', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Emerald Dragon', rarity: 'covert', weapon: 'P90' },
      { name: 'Graphite', rarity: 'classified', weapon: 'AWP' },
      { name: 'Desert Strike', rarity: 'classified', weapon: 'M4A4' },
      { name: 'Pulse', rarity: 'classified', weapon: 'P2000' },
      { name: 'Emerald Pinstripe', rarity: 'restricted', weapon: 'AUG' },
      { name: 'Ultraviolet', rarity: 'restricted', weapon: 'Desert Eagle' },
      { name: 'Bone Mask', rarity: 'restricted', weapon: 'SG 553' },
      { name: 'Nitro', rarity: 'restricted', weapon: 'M4A4' },
      { name: 'Overgrowth', rarity: 'restricted', weapon: 'USP-S' },
      { name: 'Bright Water', rarity: 'mil-spec', weapon: 'M4A1-S' },
      { name: 'Caiman', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Green Plaid', rarity: 'mil-spec', weapon: 'Nova' },
      { name: 'Bone Pile', rarity: 'mil-spec', weapon: 'P250' },
      { name: 'Antique', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Memento', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Bone Mask', rarity: 'mil-spec', weapon: 'PP-Bizon' },
    ],
  },
  'chroma': {
    id: 'chroma',
    name: 'Chroma Case',
    year: 2015,
    releaseDate: 'January 2015',
    keyPrice: 1.45,
    type: 'weapon',
    description: 'First Chroma case with vibrant Doppler, Tiger Tooth, and Marble Fade knife finishes.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFEuh_KQJTtEuI63xIXbxqOtauyClTMEsJV1jruS89T3iQKx_BBqa2j3JpjVLFH1xpp0EQ',
    knife: 'Chroma Knives (Doppler/Tiger Tooth/Marble Fade/Damascus Steel/Rust Coat/Ultraviolet)',
    skins: [
      { name: 'Muertos', rarity: 'covert', weapon: 'Galil AR' },
      { name: 'Cyrex', rarity: 'covert', weapon: 'M4A1-S' },
      { name: 'Module', rarity: 'classified', weapon: 'Desert Eagle' },
      { name: 'Pulse', rarity: 'classified', weapon: 'Glock-18' },
      { name: 'Heat', rarity: 'classified', weapon: 'P250' },
      { name: 'Dragon Tattoo', rarity: 'restricted', weapon: 'AWP' },
      { name: 'Neon Kimono', rarity: 'restricted', weapon: 'MAC-10' },
      { name: 'Duelist', rarity: 'restricted', weapon: 'Five-SeveN' },
      { name: 'Retribution', rarity: 'restricted', weapon: 'XM1014' },
      { name: 'Nitro', rarity: 'restricted', weapon: 'AUG' },
      { name: 'Stone Cold', rarity: 'mil-spec', weapon: 'MP7' },
      { name: 'Eco', rarity: 'mil-spec', weapon: 'Sawed-Off' },
      { name: 'Green Marine', rarity: 'mil-spec', weapon: 'M249' },
      { name: 'Tiger Tooth', rarity: 'mil-spec', weapon: 'SCAR-20' },
      { name: 'Grotto', rarity: 'mil-spec', weapon: 'Nova' },
      { name: 'Origami', rarity: 'mil-spec', weapon: 'PP-Bizon' },
      { name: 'Bamboo Print', rarity: 'mil-spec', weapon: 'P90' },
    ],
  },
  'gamma': {
    id: 'gamma',
    name: 'Gamma Case',
    year: 2016,
    releaseDate: 'June 2016',
    keyPrice: 1.40,
    type: 'weapon',
    description: 'First Gamma case introducing Gamma Doppler and Autotronic knife finishes.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFYznarJJjkQ6ovjw4SPlfP3auqEl2oBuJB1j--WoY322QziqkdpZGr3IteLMlhpw4RJCv8',
    knife: 'Gamma Knives (Gamma Doppler/Autotronic/Lore/Freehand/Bright Water/Black Laminate)',
    skins: [
      { name: 'Mecha Industries', rarity: 'covert', weapon: 'M4A1-S' },
      { name: 'Kumicho Dragon', rarity: 'covert', weapon: 'R8 Revolver' },
      { name: 'Chopper', rarity: 'classified', weapon: 'AUG' },
      { name: 'Desolate Space', rarity: 'classified', weapon: 'M4A4' },
      { name: 'Weasel', rarity: 'classified', weapon: 'Glock-18' },
      { name: 'Rocket Pop', rarity: 'restricted', weapon: 'Five-SeveN' },
      { name: 'Asiimov', rarity: 'restricted', weapon: 'P90' },
      { name: 'Photic Zone', rarity: 'restricted', weapon: 'AWP' },
      { name: 'Kumicho Dragon', rarity: 'restricted', weapon: 'Tec-9' },
      { name: 'Oxide Blaze', rarity: 'restricted', weapon: 'SCAR-20' },
      { name: 'Praetorian', rarity: 'mil-spec', weapon: 'PP-Bizon' },
      { name: 'Moonrise', rarity: 'mil-spec', weapon: 'Nova' },
      { name: 'Worm God', rarity: 'mil-spec', weapon: 'SG 553' },
      { name: 'Aerial', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Popdog', rarity: 'mil-spec', weapon: 'P250' },
      { name: 'Judgement of Anubis', rarity: 'mil-spec', weapon: 'Desert Eagle' },
      { name: 'Tiger Moth', rarity: 'mil-spec', weapon: 'Sawed-Off' },
    ],
  },
  'fever': {
    id: 'fever',
    name: 'Fever Case',
    year: 2025,
    releaseDate: 'March 2025',
    keyPrice: 2.50,
    type: 'weapon',
    description: 'Latest CS2 case featuring the AWP Printstream and FAMAS Bad Trip as coverts.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFQ1naqRJGUXvdnnwITTxKH2YejTkjJSucEo37jE9tT33wHl-UVrYG77I9KLMlhpPd_t_bY',
    knife: 'Kukri Knife',
    skins: [
      { name: 'Printstream', rarity: 'covert', weapon: 'AWP' },
      { name: 'Bad Trip', rarity: 'covert', weapon: 'FAMAS' },
      { name: 'Searing Rage', rarity: 'classified', weapon: 'AK-47' },
      { name: 'Shinobu', rarity: 'classified', weapon: 'Glock-18' },
      { name: 'K.O. Factory', rarity: 'classified', weapon: 'UMP-45' },
      { name: 'Serpent Strike', rarity: 'restricted', weapon: 'Desert Eagle' },
      { name: 'Tosai', rarity: 'restricted', weapon: 'Zeus x27' },
      { name: 'Rising Sun', rarity: 'restricted', weapon: 'Nova' },
      { name: 'Control', rarity: 'restricted', weapon: 'Galil AR' },
      { name: 'Wave Breaker', rarity: 'restricted', weapon: 'P90' },
      { name: 'Choppa', rarity: 'mil-spec', weapon: 'M4A4' },
      { name: 'Resupply', rarity: 'mil-spec', weapon: 'MAG-7' },
      { name: 'Memorial', rarity: 'mil-spec', weapon: 'SSG 08' },
      { name: 'Sure Grip', rarity: 'mil-spec', weapon: 'P2000' },
      { name: 'PC-GRN', rarity: 'mil-spec', weapon: 'USP-S' },
      { name: 'Nexus', rarity: 'mil-spec', weapon: 'MP9' },
      { name: 'Mockingbird', rarity: 'mil-spec', weapon: 'XM1014' },
    ],
  },
  'horizon': {
    id: 'horizon',
    name: 'Horizon Case',
    year: 2018,
    releaseDate: 'August 2018',
    keyPrice: 1.50,
    type: 'weapon',
    description: 'Features the AK-47 Neon Rider and Desert Eagle Code Red with Horizon Knives.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFUwnfbOdDgavYXukYTZkqf2ZbrTwmkE6scgj7CY94ml3FXl-ENkMW3wctOLMlhpVHKV9YA',
    knife: 'Horizon Knives',
    skins: [
      { name: 'Neon Rider', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Code Red', rarity: 'covert', weapon: 'Desert Eagle' },
      { name: 'Nightmare', rarity: 'classified', weapon: 'M4A1-S' },
      { name: 'Devourer', rarity: 'classified', weapon: 'Sawed-Off' },
      { name: 'Eye of Athena', rarity: 'classified', weapon: 'FAMAS' },
      { name: 'Eco', rarity: 'restricted', weapon: 'CZ75-Auto' },
      { name: 'High Seas', rarity: 'restricted', weapon: 'G3SG1' },
      { name: 'Toy Soldier', rarity: 'restricted', weapon: 'Nova' },
      { name: 'PAW', rarity: 'restricted', weapon: 'AWP' },
      { name: 'Powercore', rarity: 'restricted', weapon: 'MP7' },
      { name: 'Amber Slipstream', rarity: 'mil-spec', weapon: 'AUG' },
      { name: 'Shred', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Warhawk', rarity: 'mil-spec', weapon: 'Glock-18' },
      { name: 'Capillary', rarity: 'mil-spec', weapon: 'MP9' },
      { name: 'Traction', rarity: 'mil-spec', weapon: 'P90' },
      { name: 'Survivalist', rarity: 'mil-spec', weapon: 'R8 Revolver' },
      { name: 'Snek-9', rarity: 'mil-spec', weapon: 'Tec-9' },
    ],
  },
  'spectrum': {
    id: 'spectrum',
    name: 'Spectrum Case',
    year: 2017,
    releaseDate: 'March 2017',
    keyPrice: 1.35,
    type: 'weapon',
    description: 'First Spectrum case with the AK-47 Bloodsport and USP-S Neo-Noir as coverts.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFY2nfKadD4U7Y7lwYXexaGlYb3QzjlUvZ0k0ujHptug2VbirkRrNW2md4SLMlhph09hpX0',
    knife: 'Spectrum Knives',
    skins: [
      { name: 'Bloodsport', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Neo-Noir', rarity: 'covert', weapon: 'USP-S' },
      { name: 'Fever Dream', rarity: 'classified', weapon: 'AWP' },
      { name: 'Xiangliu', rarity: 'classified', weapon: 'CZ75-Auto' },
      { name: 'Decimator', rarity: 'classified', weapon: 'M4A1-S' },
      { name: 'Crimson Tsunami', rarity: 'restricted', weapon: 'Galil AR' },
      { name: 'Emerald Poison Dart', rarity: 'restricted', weapon: 'M249' },
      { name: 'Last Dive', rarity: 'restricted', weapon: 'MAC-10' },
      { name: 'Scaffold', rarity: 'restricted', weapon: 'UMP-45' },
      { name: 'Seasons', rarity: 'restricted', weapon: 'XM1014' },
      { name: 'Jungle Slipstream', rarity: 'mil-spec', weapon: 'PP-Bizon' },
      { name: 'Blueprint', rarity: 'mil-spec', weapon: 'SCAR-20' },
      { name: 'Oxide Blaze', rarity: 'mil-spec', weapon: 'Desert Eagle' },
      { name: 'Capillary', rarity: 'mil-spec', weapon: 'Five-SeveN' },
      { name: 'Akoben', rarity: 'mil-spec', weapon: 'MP7' },
      { name: 'Ripple', rarity: 'mil-spec', weapon: 'P250' },
      { name: 'Zander', rarity: 'mil-spec', weapon: 'Sawed-Off' },
    ],
  },
  'glove': {
    id: 'glove',
    name: 'Glove Case',
    year: 2016,
    releaseDate: 'November 2016',
    keyPrice: 3.00,
    type: 'weapon',
    description: 'Introduced the first weapon skins paired with glove drops as rare specials.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFY1naTMdzwTtNrukteIkqT2MO_Uwz5Q6cYhibyXo4rw2ALsrkRoYjuncNCLMlhpEV4XDTk',
    knife: 'Driver/Hand Wrap/Moto/Specialist Gloves',
    skins: [
      { name: 'Buzz Kill', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Dragonfire', rarity: 'covert', weapon: 'SSG 08' },
      { name: 'Mecha Industries', rarity: 'classified', weapon: 'FAMAS' },
      { name: 'Shallow Grave', rarity: 'classified', weapon: 'P90' },
      { name: 'Wasteland Princess', rarity: 'classified', weapon: 'Sawed-Off' },
      { name: 'Royal Consorts', rarity: 'restricted', weapon: 'Dual Berettas' },
      { name: 'Stinger', rarity: 'restricted', weapon: 'G3SG1' },
      { name: 'Flashback', rarity: 'restricted', weapon: 'M4A1-S' },
      { name: 'Gila', rarity: 'restricted', weapon: 'Nova' },
      { name: 'Cyrex', rarity: 'restricted', weapon: 'USP-S' },
      { name: 'Polymer', rarity: 'mil-spec', weapon: 'CZ75-Auto' },
      { name: 'Ironwork', rarity: 'mil-spec', weapon: 'Glock-18' },
      { name: 'Cirrus', rarity: 'mil-spec', weapon: 'MP7' },
      { name: 'Black Sand', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Sand Scale', rarity: 'mil-spec', weapon: 'MP9' },
      { name: 'Sonar', rarity: 'mil-spec', weapon: 'MAG-7' },
      { name: 'Turf', rarity: 'mil-spec', weapon: 'P2000' },
    ],
  },
  'gamma2': {
    id: 'gamma2',
    name: 'Gamma 2 Case',
    year: 2016,
    releaseDate: 'August 2016',
    keyPrice: 1.35,
    type: 'weapon',
    description: 'Second Gamma case featuring the AK-47 Neon Revolution and FAMAS Roll Cage.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsVFx5KAVo5PSkKV4xhfGfKTgVvIXlxNPSwaOmMLiGwzgJvJMniO-Zoo_z2wXg-EVvfSmtc78HsNoy',
    knife: 'Gamma Knives',
    skins: [
      { name: 'Neon Revolution', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Roll Cage', rarity: 'covert', weapon: 'FAMAS' },
      { name: 'Syd Mead', rarity: 'classified', weapon: 'AUG' },
      { name: 'Airlock', rarity: 'classified', weapon: 'MP9' },
      { name: 'Fuel Injector', rarity: 'classified', weapon: 'Tec-9' },
      { name: 'Directive', rarity: 'restricted', weapon: 'Desert Eagle' },
      { name: 'Weasel', rarity: 'restricted', weapon: 'Glock-18' },
      { name: 'Petroglyph', rarity: 'restricted', weapon: 'MAG-7' },
      { name: 'Powercore', rarity: 'restricted', weapon: 'SCAR-20' },
      { name: 'Triarch', rarity: 'restricted', weapon: 'SG 553' },
      { name: 'Imprint', rarity: 'mil-spec', weapon: 'CZ75-Auto' },
      { name: 'Scumbria', rarity: 'mil-spec', weapon: 'Five-SeveN' },
      { name: 'Ventilator', rarity: 'mil-spec', weapon: 'G3SG1' },
      { name: 'Dazzle', rarity: 'mil-spec', weapon: 'Negev' },
      { name: 'Grim', rarity: 'mil-spec', weapon: 'P90' },
      { name: 'Briefing', rarity: 'mil-spec', weapon: 'UMP-45' },
      { name: 'Slipstream', rarity: 'mil-spec', weapon: 'XM1014' },
    ],
  },
  'chroma3': {
    id: 'chroma3',
    name: 'Chroma 3 Case',
    year: 2016,
    releaseDate: 'June 2016',
    keyPrice: 1.30,
    type: 'weapon',
    description: 'Third Chroma case with PP-Bizon Judgement of Anubis and M4A1-S Chantico\'s Fire.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFYynaSdJGhE74y0wNWIw_OlNuvXkDpSuZQmi--SrN-h3gey-Uo6YWmlIoCLMlhplhFFvwI',
    knife: 'Chroma Knives',
    skins: [
      { name: 'Chantico\'s Fire', rarity: 'covert', weapon: 'M4A1-S' },
      { name: 'Judgement of Anubis', rarity: 'covert', weapon: 'PP-Bizon' },
      { name: 'Fleet Flock', rarity: 'classified', weapon: 'AUG' },
      { name: 'Asiimov', rarity: 'classified', weapon: 'P250' },
      { name: 'Primal Saber', rarity: 'classified', weapon: 'UMP-45' },
      { name: 'Red Astor', rarity: 'restricted', weapon: 'CZ75-Auto' },
      { name: 'Firefight', rarity: 'restricted', weapon: 'Galil AR' },
      { name: 'Ghost Crusader', rarity: 'restricted', weapon: 'SSG 08' },
      { name: 'Re-Entry', rarity: 'restricted', weapon: 'Tec-9' },
      { name: 'Black Tie', rarity: 'restricted', weapon: 'XM1014' },
      { name: 'Ventilators', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Orange Crash', rarity: 'mil-spec', weapon: 'G3SG1' },
      { name: 'Spectre', rarity: 'mil-spec', weapon: 'M249' },
      { name: 'Bioleak', rarity: 'mil-spec', weapon: 'MP9' },
      { name: 'Oceanic', rarity: 'mil-spec', weapon: 'P2000' },
      { name: 'Fubar', rarity: 'mil-spec', weapon: 'Sawed-Off' },
      { name: 'Atlas', rarity: 'mil-spec', weapon: 'SG 553' },
    ],
  },
  'chroma2': {
    id: 'chroma2',
    name: 'Chroma 2 Case',
    year: 2015,
    releaseDate: 'April 2015',
    keyPrice: 1.25,
    type: 'weapon',
    description: 'Second Chroma case featuring M4A1-S Hyper Beast and MAC-10 Neon Rider.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFAuhqSaKWtEu43mxtbbk6b1a77Twm4Iu8Yl3bCU9Imii1Xt80M5MmD7JZjVLFH-6VnQJQ',
    knife: 'Chroma Knives',
    skins: [
      { name: 'Hyper Beast', rarity: 'covert', weapon: 'M4A1-S' },
      { name: 'Neon Rider', rarity: 'covert', weapon: 'MAC-10' },
      { name: 'Monkey Business', rarity: 'classified', weapon: 'Five-SeveN' },
      { name: 'Eco', rarity: 'classified', weapon: 'Galil AR' },
      { name: 'Djinn', rarity: 'classified', weapon: 'FAMAS' },
      { name: 'Worm God', rarity: 'restricted', weapon: 'AWP' },
      { name: 'Heat', rarity: 'restricted', weapon: 'MAG-7' },
      { name: 'Pole Position', rarity: 'restricted', weapon: 'CZ75-Auto' },
      { name: 'Grand Prix', rarity: 'restricted', weapon: 'UMP-45' },
      { name: 'Elite Build', rarity: 'mil-spec', weapon: 'AK-47' },
      { name: 'Armor Core', rarity: 'mil-spec', weapon: 'MP7' },
      { name: 'Bronze Deco', rarity: 'mil-spec', weapon: 'Desert Eagle' },
      { name: 'Valence', rarity: 'mil-spec', weapon: 'P250' },
      { name: 'Man-o\'-war', rarity: 'mil-spec', weapon: 'Negev' },
      { name: 'Origami', rarity: 'mil-spec', weapon: 'Sawed-Off' },
    ],
  },
  'revolver': {
    id: 'revolver',
    name: 'Revolver Case',
    year: 2015,
    releaseDate: 'December 2015',
    keyPrice: 1.20,
    type: 'weapon',
    description: 'Released alongside the R8 Revolver, featuring the first R8 skins.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFYwnfKfcG9HvN7iktaOkqD1auLTxD5SvZYgiLvFpo7xjVLh-kdrYWnzcoGLMlhpsyM-5vg',
    knife: 'Revolver Knives',
    skins: [
      { name: 'Royal Paladin', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Fade', rarity: 'covert', weapon: 'R8 Revolver' },
      { name: 'Point Disarray', rarity: 'classified', weapon: 'AK-47' },
      { name: 'The Executioner', rarity: 'classified', weapon: 'G3SG1' },
      { name: 'Shapewood', rarity: 'classified', weapon: 'P90' },
      { name: 'Fuel Rod', rarity: 'restricted', weapon: 'PP-Bizon' },
      { name: 'Retrobution', rarity: 'restricted', weapon: 'Five-SeveN' },
      { name: 'Power Loader', rarity: 'restricted', weapon: 'Negev' },
      { name: 'Tiger Moth', rarity: 'restricted', weapon: 'SG 553' },
      { name: 'Avalanche', rarity: 'restricted', weapon: 'Tec-9' },
      { name: 'Teclu Burner', rarity: 'restricted', weapon: 'XM1014' },
      { name: 'Crimson Web', rarity: 'mil-spec', weapon: 'R8 Revolver' },
      { name: 'Ricochet', rarity: 'mil-spec', weapon: 'AUG' },
      { name: 'Corinthian', rarity: 'mil-spec', weapon: 'Desert Eagle' },
      { name: 'Imperial', rarity: 'mil-spec', weapon: 'P2000' },
      { name: 'Yorick', rarity: 'mil-spec', weapon: 'Sawed-Off' },
      { name: 'Outbreak', rarity: 'mil-spec', weapon: 'SCAR-20' },
    ],
  },
  'falchion': {
    id: 'falchion',
    name: 'Falchion Case',
    year: 2015,
    releaseDate: 'May 2015',
    keyPrice: 1.15,
    type: 'weapon',
    description: 'Introduced the Falchion Knife with AK-47 Aquamarine Revenge and AWP Hyper Beast.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FF8ugPDMIWpAuIq1w4KIlaChZOyFwzgJuZNy3-2T89T0jlC2rhZla2vwIJjVLFHz75yKpg',
    knife: 'Falchion Knife',
    skins: [
      { name: 'Aquamarine Revenge', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Hyper Beast', rarity: 'covert', weapon: 'AWP' },
      { name: 'Yellow Jacket', rarity: 'classified', weapon: 'CZ75-Auto' },
      { name: 'Nemesis', rarity: 'classified', weapon: 'MP7' },
      { name: 'Cyrex', rarity: 'classified', weapon: 'SG 553' },
      { name: 'Neural Net', rarity: 'restricted', weapon: 'FAMAS' },
      { name: 'Evil Daimyo', rarity: 'restricted', weapon: 'M4A4' },
      { name: 'Ruby Poison Dart', rarity: 'restricted', weapon: 'MP9' },
      { name: 'Loudmouth', rarity: 'restricted', weapon: 'Negev' },
      { name: 'Handgun', rarity: 'restricted', weapon: 'P2000' },
      { name: 'Rocket Pop', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Bunsen Burner', rarity: 'mil-spec', weapon: 'Glock-18' },
      { name: 'Ranger', rarity: 'mil-spec', weapon: 'Nova' },
      { name: 'Elite Build', rarity: 'mil-spec', weapon: 'P90' },
      { name: 'Riot', rarity: 'mil-spec', weapon: 'UMP-45' },
      { name: 'Torque', rarity: 'mil-spec', weapon: 'USP-S' },
    ],
  },
  'shadow': {
    id: 'shadow',
    name: 'Shadow Case',
    year: 2015,
    releaseDate: 'September 2015',
    keyPrice: 1.10,
    type: 'weapon',
    description: 'Introduced Shadow Daggers with M4A1-S Golden Coil and USP-S Kill Confirmed.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FF4u1qubIW4Su4mzxYHbzqGtZ-KGlz8EuJcg3rnE9NiijVe3_UY-Zzr2JJjVLFEEeiQRtg',
    knife: 'Shadow Daggers',
    skins: [
      { name: 'Golden Coil', rarity: 'covert', weapon: 'M4A1-S' },
      { name: 'Kill Confirmed', rarity: 'covert', weapon: 'USP-S' },
      { name: 'Frontside Misty', rarity: 'classified', weapon: 'AK-47' },
      { name: 'Flux', rarity: 'classified', weapon: 'G3SG1' },
      { name: 'Big Iron', rarity: 'classified', weapon: 'SSG 08' },
      { name: 'Stone Cold', rarity: 'restricted', weapon: 'Galil AR' },
      { name: 'Nebula Crusader', rarity: 'restricted', weapon: 'M249' },
      { name: 'Special Delivery', rarity: 'restricted', weapon: 'MP7' },
      { name: 'Wingshot', rarity: 'restricted', weapon: 'P250' },
      { name: 'Dualing Dragons', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Survivor Z', rarity: 'mil-spec', weapon: 'FAMAS' },
      { name: 'Wraiths', rarity: 'mil-spec', weapon: 'Glock-18' },
      { name: 'Rangeen', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Cobalt Core', rarity: 'mil-spec', weapon: 'MAG-7' },
      { name: 'Green Marine', rarity: 'mil-spec', weapon: 'SCAR-20' },
      { name: 'Scumbria', rarity: 'mil-spec', weapon: 'XM1014' },
    ],
  },
  'operation-wildfire': {
    id: 'operation-wildfire',
    name: 'Operation Wildfire Case',
    year: 2016,
    releaseDate: 'February 2016',
    keyPrice: 1.05,
    type: 'weapon',
    description: 'Released with Operation Wildfire featuring AK-47 Fuel Injector and M4A4 The Battlestar.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFYxnaeQImRGu4S1x9TawfSmY-iHkmoD7cEl2LiQpIjz3wPl_ERkYWHwLY-LMlhp9pkR_UQ',
    knife: 'Bowie Knife',
    skins: [
      { name: 'Fuel Injector', rarity: 'covert', weapon: 'AK-47' },
      { name: 'The Battlestar', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Elite Build', rarity: 'classified', weapon: 'AWP' },
      { name: 'Kumicho Dragon', rarity: 'classified', weapon: 'Desert Eagle' },
      { name: 'Hyper Beast', rarity: 'classified', weapon: 'Nova' },
      { name: 'Valence', rarity: 'restricted', weapon: 'FAMAS' },
      { name: 'Triumvirate', rarity: 'restricted', weapon: 'Five-SeveN' },
      { name: 'Royal Legion', rarity: 'restricted', weapon: 'Glock-18' },
      { name: 'Praetorian', rarity: 'restricted', weapon: 'MAG-7' },
      { name: 'Impire', rarity: 'restricted', weapon: 'MP7' },
      { name: 'Photic Zone', rarity: 'mil-spec', weapon: 'PP-Bizon' },
      { name: 'Cartel', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Lapis Gator', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Necropos', rarity: 'mil-spec', weapon: 'SSG 08' },
      { name: 'Jambiya', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Lead Conduit', rarity: 'mil-spec', weapon: 'USP-S' },
    ],
  },
  'operation-hydra': {
    id: 'operation-hydra',
    name: 'Operation Hydra Case',
    year: 2017,
    releaseDate: 'May 2017',
    keyPrice: 1.40,
    type: 'weapon',
    description: 'Released with Operation Hydra featuring AWP Oni Taiji and Five-SeveN Hyper Beast.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFY3navMJWgQtNm1ldLZzvOiZr-BlToIsZcoi-yTpdutiVW2-Es4NWjwIo-LMlhpinMS53M',
    knife: 'Hydra Knives',
    skins: [
      { name: 'Oni Taiji', rarity: 'covert', weapon: 'AWP' },
      { name: 'Hyper Beast', rarity: 'covert', weapon: 'Five-SeveN' },
      { name: 'Cobra Strike', rarity: 'classified', weapon: 'Dual Berettas' },
      { name: 'Sugar Rush', rarity: 'classified', weapon: 'Galil AR' },
      { name: 'Hellfire', rarity: 'classified', weapon: 'M4A4' },
      { name: 'Orbit Mk01', rarity: 'restricted', weapon: 'AK-47' },
      { name: 'Woodsman', rarity: 'restricted', weapon: 'P2000' },
      { name: 'Red Rock', rarity: 'restricted', weapon: 'P250' },
      { name: 'Death Grip', rarity: 'restricted', weapon: 'P90' },
      { name: 'Death\'s Head', rarity: 'restricted', weapon: 'SSG 08' },
      { name: 'Blueprint', rarity: 'mil-spec', weapon: 'USP-S' },
      { name: 'Macabre', rarity: 'mil-spec', weapon: 'FAMAS' },
      { name: 'Briefing', rarity: 'mil-spec', weapon: 'M4A1-S' },
      { name: 'Aloha', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Hard Water', rarity: 'mil-spec', weapon: 'MAG-7' },
      { name: 'Cut Out', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Metal Flowers', rarity: 'mil-spec', weapon: 'UMP-45' },
    ],
  },
  'operation-riptide': {
    id: 'operation-riptide',
    name: 'Operation Riptide Case',
    year: 2021,
    releaseDate: 'September 2021',
    keyPrice: 2.00,
    type: 'weapon',
    description: 'Released with Operation Riptide featuring AK-47 Leet Museo and Desert Eagle Ocean Drive.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFU5narKKW4SvIrhw9PZlaPwNuqAxmgBucNz2L3C8dyj31Xn-0VtMW3wdY6LMlhplna0TPI',
    knife: 'Riptide Knives',
    skins: [
      { name: 'Leet Museo', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Ocean Drive', rarity: 'covert', weapon: 'Desert Eagle' },
      { name: 'Toybox', rarity: 'classified', weapon: 'MAC-10' },
      { name: 'Snack Attack', rarity: 'classified', weapon: 'Glock-18' },
      { name: 'Turbo Peek', rarity: 'classified', weapon: 'SSG 08' },
      { name: 'BI83 Spectrum', rarity: 'restricted', weapon: 'MAG-7' },
      { name: 'ZX Spectron', rarity: 'restricted', weapon: 'FAMAS' },
      { name: 'Boost Protocol', rarity: 'restricted', weapon: 'Five-SeveN' },
      { name: 'Mount Fuji', rarity: 'restricted', weapon: 'MP9' },
      { name: 'Spider Lily', rarity: 'restricted', weapon: 'M4A4' },
      { name: 'Plague', rarity: 'mil-spec', weapon: 'AUG' },
      { name: 'Tread', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Keeping Tabs', rarity: 'mil-spec', weapon: 'G3SG1' },
      { name: 'Guerrilla', rarity: 'mil-spec', weapon: 'MP7' },
      { name: 'Lumen', rarity: 'mil-spec', weapon: 'PP-Bizon' },
      { name: 'Black Lotus', rarity: 'mil-spec', weapon: 'USP-S' },
      { name: 'Watchdog', rarity: 'mil-spec', weapon: 'XM1014' },
    ],
  },
  'operation-broken-fang': {
    id: 'operation-broken-fang',
    name: 'Operation Broken Fang Case',
    year: 2020,
    releaseDate: 'December 2020',
    keyPrice: 1.95,
    type: 'weapon',
    description: 'Released with Operation Broken Fang featuring M4A1-S Printstream and Glock-18 Neo-Noir.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFU3naeZIWUStYjgxdnewfGmZb6DxW8AupMp27yT9IqiilCxqkRkZGyldoaLMlhp6IQjKcg',
    knife: 'Broken Fang Gloves',
    skins: [
      { name: 'Printstream', rarity: 'covert', weapon: 'M4A1-S' },
      { name: 'Neo-Noir', rarity: 'covert', weapon: 'Glock-18' },
      { name: 'Fairy Tale', rarity: 'classified', weapon: 'Five-SeveN' },
      { name: 'Cyber Security', rarity: 'classified', weapon: 'M4A4' },
      { name: 'Monster Mashup', rarity: 'classified', weapon: 'USP-S' },
      { name: 'Exoskeleton', rarity: 'restricted', weapon: 'AWP' },
      { name: 'Dezastre', rarity: 'restricted', weapon: 'Dual Berettas' },
      { name: 'Clear Polymer', rarity: 'restricted', weapon: 'Nova' },
      { name: 'Parallax', rarity: 'restricted', weapon: 'SSG 08' },
      { name: 'Gold Bismuth', rarity: 'restricted', weapon: 'UMP-45' },
      { name: 'Vendetta', rarity: 'mil-spec', weapon: 'CZ75-Auto' },
      { name: 'Cocoa Rampage', rarity: 'mil-spec', weapon: 'P90' },
      { name: 'Digital Mesh', rarity: 'mil-spec', weapon: 'G3SG1' },
      { name: 'Vandal', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Contaminant', rarity: 'mil-spec', weapon: 'P250' },
      { name: 'Deep Relief', rarity: 'mil-spec', weapon: 'M249' },
      { name: 'Condition Zero', rarity: 'mil-spec', weapon: 'MP5-SD' },
    ],
  },
  'shattered-web': {
    id: 'shattered-web',
    name: 'Shattered Web Case',
    year: 2019,
    releaseDate: 'November 2019',
    keyPrice: 1.70,
    type: 'weapon',
    description: 'Released with Operation Shattered Web featuring AWP Containment Breach and MAC-10 Stalker.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFUznaCaJWVDvozlzdONwvKjYLiBk24IsZEl0uuYrNjw0A3n80JpZWzwIYWLMlhpLvhcskA',
    knife: 'Shattered Web Knives',
    skins: [
      { name: 'Containment Breach', rarity: 'covert', weapon: 'AWP' },
      { name: 'Stalker', rarity: 'covert', weapon: 'MAC-10' },
      { name: 'Decimator', rarity: 'classified', weapon: 'Tec-9' },
      { name: 'Colony IV', rarity: 'classified', weapon: 'SG 553' },
      { name: 'Bloodshot', rarity: 'classified', weapon: 'SSG 08' },
      { name: 'Embargo', rarity: 'restricted', weapon: 'PP-Bizon' },
      { name: 'Rat Rod', rarity: 'restricted', weapon: 'AK-47' },
      { name: 'Arctic Wolf', rarity: 'restricted', weapon: 'AUG' },
      { name: 'Neon Ply', rarity: 'restricted', weapon: 'MP7' },
      { name: 'Obsidian', rarity: 'restricted', weapon: 'P2000' },
      { name: 'Acid Wash', rarity: 'mil-spec', weapon: 'MP5-SD' },
      { name: 'Plume', rarity: 'mil-spec', weapon: 'Nova' },
      { name: 'Black Sand', rarity: 'mil-spec', weapon: 'G3SG1' },
      { name: 'Memento', rarity: 'mil-spec', weapon: 'R8 Revolver' },
      { name: 'Balance', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Torn', rarity: 'mil-spec', weapon: 'SCAR-20' },
      { name: 'Warbird', rarity: 'mil-spec', weapon: 'M249' },
    ],
  },
  'operation-breakout': {
    id: 'operation-breakout',
    name: 'Operation Breakout Weapon Case',
    year: 2014,
    releaseDate: 'July 2014',
    keyPrice: 1.00,
    type: 'weapon',
    description: 'Released with Operation Breakout featuring M4A1-S Cyrex and P90 Asiimov.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFMu1aPMI24auITjxteJwPXxY72AkGgIvZAniLjHpon2jlbl-kpvNjz3JJjVLFG9rl1YLQ',
    knife: 'Butterfly Knife',
    skins: [
      { name: 'Cyrex', rarity: 'covert', weapon: 'M4A1-S' },
      { name: 'Asiimov', rarity: 'covert', weapon: 'P90' },
      { name: 'Conspiracy', rarity: 'classified', weapon: 'Desert Eagle' },
      { name: 'Fowl Play', rarity: 'classified', weapon: 'Five-SeveN' },
      { name: 'Water Elemental', rarity: 'classified', weapon: 'Glock-18' },
      { name: 'Osiris', rarity: 'restricted', weapon: 'PP-Bizon' },
      { name: 'Tigris', rarity: 'restricted', weapon: 'CZ75-Auto' },
      { name: 'Koi', rarity: 'restricted', weapon: 'Nova' },
      { name: 'Supernova', rarity: 'restricted', weapon: 'P250' },
      { name: 'Urban Hazard', rarity: 'mil-spec', weapon: 'MP7' },
      { name: 'Desert-Strike', rarity: 'mil-spec', weapon: 'Negev' },
      { name: 'Ivory', rarity: 'mil-spec', weapon: 'P2000' },
      { name: 'Abyss', rarity: 'mil-spec', weapon: 'SSG 08' },
      { name: 'Labyrinth', rarity: 'mil-spec', weapon: 'UMP-45' },
    ],
  },
  'operation-vanguard': {
    id: 'operation-vanguard',
    name: 'Operation Vanguard Weapon Case',
    year: 2014,
    releaseDate: 'November 2014',
    keyPrice: 0.95,
    type: 'weapon',
    description: 'Released with Operation Vanguard featuring AK-47 Wasteland Rebel and P2000 Fire Elemental.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFIuh6rJImVGvtjllYaNka6la7rUxWkE65BzibvD9N7z0Q22-0Fka2GlJ5jVLFHqavWW2g',
    knife: 'Huntsman Knife',
    skins: [
      { name: 'Wasteland Rebel', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Fire Elemental', rarity: 'covert', weapon: 'P2000' },
      { name: 'Cartel', rarity: 'classified', weapon: 'P250' },
      { name: 'Cardiac', rarity: 'classified', weapon: 'SCAR-20' },
      { name: 'Tranquility', rarity: 'classified', weapon: 'XM1014' },
      { name: 'Grinder', rarity: 'restricted', weapon: 'Glock-18' },
      { name: 'Basilisk', rarity: 'restricted', weapon: 'M4A1-S' },
      { name: 'Griffin', rarity: 'restricted', weapon: 'M4A4' },
      { name: 'Highwayman', rarity: 'restricted', weapon: 'Sawed-Off' },
      { name: 'Murky', rarity: 'mil-spec', weapon: 'G3SG1' },
      { name: 'Firestarter', rarity: 'mil-spec', weapon: 'MAG-7' },
      { name: 'Dart', rarity: 'mil-spec', weapon: 'MP9' },
      { name: 'Urban Hazard', rarity: 'mil-spec', weapon: 'Five-SeveN' },
      { name: 'Delusion', rarity: 'mil-spec', weapon: 'UMP-45' },
    ],
  },
  'operation-phoenix': {
    id: 'operation-phoenix',
    name: 'Operation Phoenix Weapon Case',
    year: 2014,
    releaseDate: 'February 2014',
    keyPrice: 0.90,
    type: 'weapon',
    description: 'Released with Operation Phoenix featuring AWP Asiimov and AK-47 Redline.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFUuh6qZJmlD7tiyl4OIlaGhYuLTzjhVupJ12urH89ii3lHlqEdoMDr2I5jVLFFSv_J2Rg',
    knife: 'Original Knives',
    skins: [
      { name: 'Asiimov', rarity: 'covert', weapon: 'AWP' },
      { name: 'Chameleon', rarity: 'covert', weapon: 'AUG' },
      { name: 'Redline', rarity: 'classified', weapon: 'AK-47' },
      { name: 'Trigon', rarity: 'classified', weapon: 'P90' },
      { name: 'Antique', rarity: 'classified', weapon: 'Nova' },
      { name: 'Heat', rarity: 'restricted', weapon: 'MAC-10' },
      { name: 'Pulse', rarity: 'restricted', weapon: 'SG 553' },
      { name: 'Sergeant', rarity: 'restricted', weapon: 'FAMAS' },
      { name: 'Guardian', rarity: 'restricted', weapon: 'USP-S' },
      { name: 'Corporal', rarity: 'mil-spec', weapon: 'UMP-45' },
      { name: 'Terrain', rarity: 'mil-spec', weapon: 'Negev' },
      { name: 'Sandstorm', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Heaven Guard', rarity: 'mil-spec', weapon: 'MAG-7' },
    ],
  },
  'huntsman': {
    id: 'huntsman',
    name: 'Huntsman Weapon Case',
    year: 2014,
    releaseDate: 'May 2014',
    keyPrice: 0.85,
    type: 'weapon',
    description: 'Introduced the Huntsman Knife featuring AK-47 Vulcan and M4A4 Desert-Strike.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFQu0PaQIm9DtY6wzYaIxKWtN7iJwW8G6Z0h2LqWoY6s2Qy2-0Q_Nzv7IJjVLFGZqUbjlQ',
    knife: 'Huntsman Knife',
    skins: [
      { name: 'Vulcan', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Desert-Strike', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Atomic Alloy', rarity: 'classified', weapon: 'M4A1-S' },
      { name: 'Cyrex', rarity: 'classified', weapon: 'SCAR-20' },
      { name: 'Caiman', rarity: 'classified', weapon: 'USP-S' },
      { name: 'Torque', rarity: 'restricted', weapon: 'AUG' },
      { name: 'Antique', rarity: 'restricted', weapon: 'PP-Bizon' },
      { name: 'Heaven Guard', rarity: 'restricted', weapon: 'XM1014' },
      { name: 'Tatter', rarity: 'restricted', weapon: 'MAC-10' },
      { name: 'Isaac', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Slashed', rarity: 'mil-spec', weapon: 'SSG 08' },
      { name: 'Kami', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Twist', rarity: 'mil-spec', weapon: 'CZ75-Auto' },
      { name: 'Module', rarity: 'mil-spec', weapon: 'P90' },
      { name: 'Pulse', rarity: 'mil-spec', weapon: 'P2000' },
    ],
  },
  'winter-offensive': {
    id: 'winter-offensive',
    name: 'Winter Offensive Weapon Case',
    year: 2013,
    releaseDate: 'December 2013',
    keyPrice: 0.80,
    type: 'weapon',
    description: 'Holiday-themed case featuring M4A4 Asiimov and AWP Redline.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFYu0aKfJz8a793gxNLfzvOkMunUwWgH7JIjj-qW8d7x2VXt_UBuMT3zIpjVLFEGDSGUSQ',
    knife: 'Original Knives',
    skins: [
      { name: 'Asiimov', rarity: 'covert', weapon: 'M4A4' },
      { name: 'The Kraken', rarity: 'covert', weapon: 'Sawed-Off' },
      { name: 'Guardian', rarity: 'classified', weapon: 'M4A1-S' },
      { name: 'Mehndi', rarity: 'classified', weapon: 'P250' },
      { name: 'Redline', rarity: 'classified', weapon: 'AWP' },
      { name: 'Pulse', rarity: 'restricted', weapon: 'FAMAS' },
      { name: 'Marina', rarity: 'restricted', weapon: 'Dual Berettas' },
      { name: 'Rose Iron', rarity: 'restricted', weapon: 'MP9' },
      { name: 'Rising Skull', rarity: 'restricted', weapon: 'Nova' },
      { name: 'Sandstorm', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Kami', rarity: 'mil-spec', weapon: 'Five-SeveN' },
      { name: 'Magma', rarity: 'mil-spec', weapon: 'M249' },
      { name: 'Cobalt Halftone', rarity: 'mil-spec', weapon: 'PP-Bizon' },
    ],
  },
  'csgo-weapon-case': {
    id: 'csgo-weapon-case',
    name: 'CS:GO Weapon Case',
    year: 2013,
    releaseDate: 'August 2013',
    keyPrice: 0.65,
    type: 'weapon',
    description: 'The original CS:GO weapon case featuring AWP Lightning Strike and AK-47 Case Hardened.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsRVx4MwFo5_T3eAQ3i6DMIW0X7ojiwoHax6egMOKGxj4G68Nz3-jCp4itjFWx-ktqfSmtcwqVx6sT',
    knife: 'Original Knives',
    skins: [
      { name: 'Lightning Strike', rarity: 'covert', weapon: 'AWP' },
      { name: 'Case Hardened', rarity: 'classified', weapon: 'AK-47' },
      { name: 'Hypnotic', rarity: 'classified', weapon: 'Desert Eagle' },
      { name: 'Dragon Tattoo', rarity: 'restricted', weapon: 'Glock-18' },
      { name: 'Dark Water', rarity: 'restricted', weapon: 'USP-S' },
      { name: 'Dark Water', rarity: 'restricted', weapon: 'M4A1-S' },
      { name: 'Skulls', rarity: 'mil-spec', weapon: 'MP7' },
      { name: 'Wings', rarity: 'mil-spec', weapon: 'AUG' },
      { name: 'Ultraviolet', rarity: 'mil-spec', weapon: 'SG 553' },
    ],
  },
  'csgo-weapon-case-2': {
    id: 'csgo-weapon-case-2',
    name: 'CS:GO Weapon Case 2',
    year: 2013,
    releaseDate: 'September 2013',
    keyPrice: 0.70,
    type: 'weapon',
    description: 'Second CS:GO weapon case featuring SSG 08 Blood in the Water.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsRVx4MwFo5PT8elUwgKKZJmtEvo_kxITZk6StNe-Fz2pTu8Aj3eqVpIqgjVfjrRI9fSmtc1Nw-Kh3',
    knife: 'Original Knives',
    skins: [
      { name: 'Blood in the Water', rarity: 'covert', weapon: 'SSG 08' },
      { name: 'Cold Blooded', rarity: 'classified', weapon: 'P90' },
      { name: 'Serum', rarity: 'classified', weapon: 'USP-S' },
      { name: 'Case Hardened', rarity: 'restricted', weapon: 'Five-SeveN' },
      { name: 'Hypnotic', rarity: 'restricted', weapon: 'MP9' },
      { name: 'Graphite', rarity: 'restricted', weapon: 'Nova' },
      { name: 'Hemoglobin', rarity: 'restricted', weapon: 'Dual Berettas' },
      { name: 'Blue Titanium', rarity: 'mil-spec', weapon: 'Tec-9' },
      { name: 'Blood Tiger', rarity: 'mil-spec', weapon: 'M4A1-S' },
      { name: 'Hexane', rarity: 'mil-spec', weapon: 'FAMAS' },
      { name: 'Hive', rarity: 'mil-spec', weapon: 'P250' },
      { name: 'Crimson Web', rarity: 'mil-spec', weapon: 'SCAR-20' },
    ],
  },
  'csgo-weapon-case-3': {
    id: 'csgo-weapon-case-3',
    name: 'CS:GO Weapon Case 3',
    year: 2014,
    releaseDate: 'February 2014',
    keyPrice: 0.75,
    type: 'weapon',
    description: 'Third CS:GO weapon case featuring CZ75-Auto Victoria.',
    image: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsRVx4MwFo5fSnf15k0KGacG0UtYXnzdTdkq-gariGlDgHvMcmjryZotqg2wCxrUVtfSmtc20v4quI',
    knife: 'Original Knives',
    skins: [
      { name: 'Victoria', rarity: 'covert', weapon: 'CZ75-Auto' },
      { name: 'The Fuschia Is Now', rarity: 'classified', weapon: 'CZ75-Auto' },
      { name: 'Undertow', rarity: 'classified', weapon: 'P250' },
      { name: 'Tread Plate', rarity: 'restricted', weapon: 'CZ75-Auto' },
      { name: 'Titanium Bit', rarity: 'restricted', weapon: 'Tec-9' },
      { name: 'Heirloom', rarity: 'restricted', weapon: 'Desert Eagle' },
      { name: 'Copper Galaxy', rarity: 'restricted', weapon: 'Five-SeveN' },
      { name: 'Crimson Web', rarity: 'mil-spec', weapon: 'CZ75-Auto' },
      { name: 'Red FragCam', rarity: 'mil-spec', weapon: 'P2000' },
      { name: 'Panther', rarity: 'mil-spec', weapon: 'Dual Berettas' },
      { name: 'Stainless', rarity: 'mil-spec', weapon: 'USP-S' },
      { name: 'Blue Fissure', rarity: 'mil-spec', weapon: 'Glock-18' },
    ],
  },
  'esports-2013': {
    id: 'esports-2013',
    name: 'eSports 2013 Case',
    year: 2013,
    releaseDate: 'August 2013',
    keyPrice: 1.00,
    type: 'weapon',
    description: 'First eSports case supporting competitive CS:GO tournaments.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsVk5kKhZDpYX3e1YznfCcdzkR74vnw9TZwa-sYOOCzzoF6ZJ0jL6Qp9uj3Qbj_Uc6Z2z1I9WLMlhp9VPHu3g',
    knife: 'Original Knives',
    skins: [
      { name: 'Death by Kitty', rarity: 'covert', weapon: 'P90' },
      { name: 'Red Laminate', rarity: 'classified', weapon: 'AK-47' },
      { name: 'BOOM', rarity: 'classified', weapon: 'AWP' },
      { name: 'Orange DDPAT', rarity: 'restricted', weapon: 'Galil AR' },
      { name: 'Orange DDPAT', rarity: 'restricted', weapon: 'Sawed-Off' },
      { name: 'Splash', rarity: 'restricted', weapon: 'P250' },
      { name: 'Faded Zebra', rarity: 'mil-spec', weapon: 'M4A4' },
      { name: 'Memento', rarity: 'mil-spec', weapon: 'MAG-7' },
      { name: 'Doomkitty', rarity: 'mil-spec', weapon: 'FAMAS' },
    ],
  },
  'esports-2013-winter': {
    id: 'esports-2013-winter',
    name: 'eSports 2013 Winter Case',
    year: 2013,
    releaseDate: 'December 2013',
    keyPrice: 1.00,
    type: 'weapon',
    description: 'Winter eSports case featuring M4A4 X-Ray and AWP Electric Hive.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsVk5kKhZDpYX3e1Yz7KKcPzwav9jnzdfdlfWmY7_TzmkF6ZMlj77A9o3x0Qe1qhBkZGjxI9LBJgMgIQaH1G7WeaA',
    knife: 'Original Knives',
    skins: [
      { name: 'X-Ray', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Afterimage', rarity: 'classified', weapon: 'FAMAS' },
      { name: 'Electric Hive', rarity: 'classified', weapon: 'AWP' },
      { name: 'Cobalt Disruption', rarity: 'classified', weapon: 'Desert Eagle' },
      { name: 'Blue Laminate', rarity: 'restricted', weapon: 'AK-47' },
      { name: 'Blind Spot', rarity: 'restricted', weapon: 'P90' },
      { name: 'Blue Titanium', rarity: 'mil-spec', weapon: 'Galil AR' },
      { name: 'Nightshade', rarity: 'mil-spec', weapon: 'Five-SeveN' },
      { name: 'Water Sigil', rarity: 'mil-spec', weapon: 'PP-Bizon' },
      { name: 'Ghost Camo', rarity: 'mil-spec', weapon: 'Nova' },
      { name: 'Azure Zebra', rarity: 'mil-spec', weapon: 'G3SG1' },
      { name: 'Steel Disruption', rarity: 'mil-spec', weapon: 'P250' },
    ],
  },
  'esports-2014-summer': {
    id: 'esports-2014-summer',
    name: 'eSports 2014 Summer Case',
    year: 2014,
    releaseDate: 'July 2014',
    keyPrice: 1.00,
    type: 'weapon',
    description: 'Summer eSports case featuring M4A4 Bullet Rain and AK-47 Jaguar.',
    image: 'https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsVk5kKhZDpYX3e1Y07ODdfDBH_pKzwdfSkqTyZLjQxjsF7sEoiLyQ9I2ljgHt_EZlYzr6J4DHIA9oZ1-D5BHglkR7Cs6C',
    knife: 'Original Knives',
    skins: [
      { name: 'Bullet Rain', rarity: 'covert', weapon: 'M4A4' },
      { name: 'Jaguar', rarity: 'covert', weapon: 'AK-47' },
      { name: 'Bengal Tiger', rarity: 'classified', weapon: 'AUG' },
      { name: 'Bloomstick', rarity: 'classified', weapon: 'Nova' },
      { name: 'Corticera', rarity: 'classified', weapon: 'AWP' },
      { name: 'Corticera', rarity: 'classified', weapon: 'P2000' },
      { name: 'Blue Streak', rarity: 'restricted', weapon: 'PP-Bizon' },
      { name: 'Virus', rarity: 'restricted', weapon: 'P90' },
      { name: 'Ocean Foam', rarity: 'restricted', weapon: 'MP7' },
      { name: 'Steel Disruption', rarity: 'restricted', weapon: 'Glock-18' },
      { name: 'Crimson Web', rarity: 'restricted', weapon: 'Desert Eagle' },
      { name: 'Dark Water', rarity: 'mil-spec', weapon: 'SSG 08' },
      { name: 'Ultraviolet', rarity: 'mil-spec', weapon: 'MAC-10' },
      { name: 'Blood Tiger', rarity: 'mil-spec', weapon: 'USP-S' },
      { name: 'Hexane', rarity: 'mil-spec', weapon: 'CZ75-Auto' },
      { name: 'Bratatat', rarity: 'mil-spec', weapon: 'Negev' },
      { name: 'Red Python', rarity: 'mil-spec', weapon: 'XM1014' },
    ],
  },
};
