export interface MapCallout {
  name: string;
  area: 'ct' | 't' | 'mid';
  description: string;
}

export interface MapStrategy {
  title: string;
  side: 'ct' | 't';
  description: string;
}

export interface MapCalloutData {
  slug: string;
  name: string;
  description: string;
  callouts: MapCallout[];
  tips: string[];
  tags: string[];
  strategies: MapStrategy[];
}

export const MAP_CALLOUTS: MapCalloutData[] = [
  {
    slug: 'mirage', name: 'Mirage',
    description: 'A balanced map with strong mid control and two distinct bombsites. Mirage emphasizes tactical play with multiple rotations and tight angles that reward smarter positioning over raw firepower.',
    callouts: [
      { name: 'A Site', area: 'ct', description: 'The main A bombsite area. Hold from ramp, stairs, or CT for defense.' },
      { name: 'A Ramp', area: 'ct', description: 'Elevated ramp connecting mid to A site. Critical for CT control.' },
      { name: 'Palace', area: 'ct', description: 'Structure above A ramp with rooms. Key for early picks or A stack.' },
      { name: 'Stairs', area: 'ct', description: 'Stairs from CT base to A Ramp. Quick rotation to A site.' },
      { name: 'CT Spawn', area: 'ct', description: 'CT starting area behind A site. Safe for regrouping.' },
      { name: 'Jungle', area: 'ct', description: 'Plant area between A site and connector. Strong crossfire position.' },
      { name: 'B Site', area: 'ct', description: 'Second bombsite behind apartments. Multiple defender positions.' },
      { name: 'B Apartments', area: 'ct', description: 'Residential area leading to B. Strong for info and site control.' },
      { name: 'Short (Cat)', area: 'ct', description: 'Narrow passage connecting mid to B short. High-traffic route.' },
      { name: 'Kitchen', area: 'ct', description: 'Room behind B site providing cover and rotation options.' },
      { name: 'T Spawn', area: 't', description: 'T-side starting area. Safe zone for organizing executes.' },
      { name: 'Top Mid', area: 't', description: 'T-side entry to mid area. Initial position for mid takes.' },
      { name: 'Underpass', area: 't', description: 'Tunnel from T spawn toward A short. Sneaky rotate path.' },
      { name: 'T Ramp', area: 't', description: 'Ramp from T spawn toward A site. Primary A execute route.' },
      { name: 'B Apps Entrance', area: 't', description: 'Entry to B apartments from T side. Main B approach path.' },
      { name: 'Window', area: 't', description: 'Window overlooking B short and mid. Aggressive info position.' },
      { name: 'Mid', area: 'mid', description: 'Central area of the map. Critical for gaining map control.' },
      { name: 'Connector', area: 'mid', description: 'Passage connecting mid to A site. High-traffic position.' },
      { name: 'Catwalk', area: 'mid', description: 'Elevated path above B site. Height advantage for mid players.' },
      { name: 'Mid Boxes', area: 'mid', description: 'Box cover in mid area. Contested position during mid fights.' },
      { name: 'Ladder Room', area: 'mid', description: 'Room with ladder between mid and short. Alternate route.' },
    ],
    tips: [
      'Control mid early to dictate the round. Winning mid gives T-side flexibility to hit A or B.',
      'Communication matters more on Mirage. The many rotation paths demand precise callouts.',
      'Play tight angles as CT. Many corners favor defenders when positioned correctly.',
      'Utility usage is critical. Key smokes around A Ramp and mid control the pace of every round.',
      'Practice your default positions. Crosshair placement and angle knowledge wins rounds.',
    ],
    tags: ['Balanced', 'Mid Control', 'Tactical', 'Active Duty'],
    strategies: [
      { title: 'A Ramp Rush', side: 't', description: 'Push A Ramp with smokes for stairs and CT, flashes for site. Fast plant with post-plant coverage from palace and ramp.' },
      { title: 'B Apartments Execute', side: 't', description: 'Stack B apartments, smoke short and kitchen, flash site. Overwhelming numbers through apps.' },
      { title: 'Mid-to-A Split', side: 't', description: 'Take mid control, split to A from connector and ramp simultaneously with coordinated utility.' },
      { title: 'A Anchor Defense', side: 'ct', description: 'Play one player stairs, one jungle. Use utility to delay ramp pushes and get info from palace.' },
    ],
  },
  {
    slug: 'inferno', name: 'Inferno',
    description: 'A map that rewards coordinated utility usage and teamwork. Tight chokepoints on banana and apartments create intense firefights that demand precise grenade work and trade fragging.',
    callouts: [
      { name: 'A Site', area: 'ct', description: 'Main A bombsite with truck, pit, and balcony positions.' },
      { name: 'Pit', area: 'ct', description: 'Sunken area near A site. Strong defensive position with low exposure.' },
      { name: 'Library', area: 'ct', description: 'Building overlooking A site and short. Key defensive angle.' },
      { name: 'Arch', area: 'ct', description: 'Archway connecting CT to A site. Primary rotation route.' },
      { name: 'CT Spawn', area: 'ct', description: 'CT starting area with buy zone. Central position between sites.' },
      { name: 'B Site', area: 'ct', description: 'Second bombsite in courtyard area. Vulnerable position requiring utility.' },
      { name: 'Construction', area: 'ct', description: 'Elevated construction area near B. Strong position for site defense.' },
      { name: 'Fountain', area: 'ct', description: 'Fountain area near B site. Cover position for B defenders.' },
      { name: 'Coffins', area: 'ct', description: 'Coffin area between sites. Rotation and holding position.' },
      { name: 'Spools', area: 'ct', description: 'Spool cover on B site. Common defensive position.' },
      { name: 'T Spawn', area: 't', description: 'T-side starting position. Central coordination point.' },
      { name: 'Banana', area: 't', description: 'Narrow passage to B site. Primary B approach with key choke.' },
      { name: 'Top Banana', area: 't', description: 'Upper section of banana near T base. Initial B approach.' },
      { name: 'Bottom Banana', area: 't', description: 'Lower banana near B site. Final approach before site.' },
      { name: 'Second Mid', area: 't', description: 'Second mid area connecting to A approaches. Alternative A route.' },
      { name: 'Apartments', area: 't', description: 'Residential area leading toward A site. Primary A approach.' },
      { name: 'Boiler', area: 't', description: 'Boiler room near B site apartments. Close-quarters position.' },
      { name: 'Mid', area: 'mid', description: 'Central area between alt-mid and arch. Map control position.' },
      { name: 'Mexico', area: 'mid', description: 'Area between T apps and mid. Rotation and info position.' },
      { name: 'Hay', area: 'mid', description: 'Hay bale area in mid. Cover position during mid fights.' },
      { name: 'Bridge', area: 'mid', description: 'Bridge over mid area. Elevated crossing between areas.' },
    ],
    tips: [
      'Master banana control. B site access depends on winning the banana fight with utility.',
      'Use molotovs aggressively. Clearing common positions with fire is essential on Inferno.',
      'Trade kills instantly. The tight angles mean you must be ready to refrag teammates.',
      'Learn arch-side smokes. Controlling arch access is crucial for A site security.',
      'Play crossfire setups. The map rewards coordinated angles from multiple positions.',
    ],
    tags: ['Utility Heavy', 'Trade Kills', 'Choke Points', 'Active Duty'],
    strategies: [
      { title: 'Banana Control B Execute', side: 't', description: 'Take banana with utility, smoke coffins and CT, molly spools. Execute B with full team commitment.' },
      { title: 'Apartments A Split', side: 't', description: 'Take apartments, split through arch and short. Coordinate with players from second mid.' },
      { title: 'Fast B Rush', side: 't', description: 'Full team banana rush with utility stack. Overwhelming speed before CTs can rotate.' },
      { title: 'Banana Aggression CT', side: 'ct', description: 'Push banana early with utility. Get info and damage before falling back to site.' },
    ],
  },
  {
    slug: 'dust2', name: 'Dust 2',
    description: 'The most iconic Counter-Strike map. A simple three-lane layout with long sightlines and fast-paced gameplay. Perfect for learning fundamentals with a balanced design rewarding both aim and strategy.',
    callouts: [
      { name: 'A Site', area: 'ct', description: 'A bombsite with platform, goose corner, and car positions.' },
      { name: 'Goose', area: 'ct', description: 'Corner behind A platform. Named after graffiti, common afterplant spot.' },
      { name: 'A Car', area: 'ct', description: 'Car on A site providing cover. Afterplant and defense position.' },
      { name: 'A Short', area: 'ct', description: 'Short A / Catwalk from mid to A site. Elevated approach.' },
      { name: 'Long A', area: 'ct', description: 'Long corridor to A site with doors. Classic AWP duel area.' },
      { name: 'Pit', area: 'ct', description: 'Pit area near A long. Strong defensive position with cover.' },
      { name: 'CT Spawn', area: 'ct', description: 'CT starting area. Central position for both site rotations.' },
      { name: 'B Site', area: 'ct', description: 'B bombsite with back platform, window, and car positions.' },
      { name: 'B Window', area: 'ct', description: 'Window overlooking B tunnels entrance. Strong hold position.' },
      { name: 'B Car', area: 'ct', description: 'Car on B site for cover during retakes and defense.' },
      { name: 'B Back Platform', area: 'ct', description: 'Elevated platform at back of B. Height advantage position.' },
      { name: 'T Spawn', area: 't', description: 'T starting area. Three routes: long, short via mid, or tunnels.' },
      { name: 'Long Doors', area: 't', description: 'Double doors on long A. Famous AWP battle position.' },
      { name: 'Outside Long', area: 't', description: 'Area outside long doors. T-side staging for long pushes.' },
      { name: 'Upper Tunnels', area: 't', description: 'Upper B tunnels from T spawn toward B site.' },
      { name: 'Lower Tunnels', area: 't', description: 'Lower tunnels connecting T spawn to upper tunnels.' },
      { name: 'Mid', area: 'mid', description: 'Central corridor connecting T spawn to both sites.' },
      { name: 'Mid Doors', area: 'mid', description: 'Doors in mid. Famous AWP position at round start.' },
      { name: 'Xbox', area: 'mid', description: 'Box in mid used for boosting to short A. Key position.' },
      { name: 'Suicide', area: 'mid', description: 'Exposed mid area from T spawn. High risk info position.' },
    ],
    tips: [
      'Dust 2 is about fundamentals. Master spraying, counter-strafing, and aim duels.',
      'Mid control determines the round. Winning early mid fights gives attackers flexibility.',
      'Long A is an AWP playground. Practice your long-range duels or learn the smokes.',
      'Rotate quickly. The simple layout means both teams can reach sites fast.',
      'Use smokes efficiently. Crossing long doors and blocking mid are essential skills.',
    ],
    tags: ['Iconic', 'Balanced', 'Fundamentals', 'Active Duty'],
    strategies: [
      { title: 'Long A Take', side: 't', description: 'Rush long with flashes, smoke CT cross, take A site from long and short simultaneously.' },
      { title: 'B Tunnels Rush', side: 't', description: 'Full stack upper tunnels, flash out, overwhelm B site before rotation arrives.' },
      { title: 'Mid to B Split', side: 't', description: 'Take mid control, split B from mid doors and tunnels with coordinated utility.' },
      { title: 'Long Hold Defense', side: 'ct', description: 'AWP long doors, one player short, rotate based on T-side commitment.' },
    ],
  },
  {
    slug: 'anubis', name: 'Anubis',
    description: 'A complex multi-level map with Egyptian temple architecture. Anubis rewards smart positioning, vertical gameplay, and coordinated utility usage, making it one of the more strategic active duty maps.',
    callouts: [
      { name: 'A Site', area: 'ct', description: 'First bombsite with multiple elevation levels and cover positions.' },
      { name: 'A Main', area: 'ct', description: 'Main corridor leading to A site. Primary defense position.' },
      { name: 'Ruins', area: 'ct', description: 'Ruined structures near A site providing cover.' },
      { name: 'Palace', area: 'ct', description: 'Palace structure overlooking A. Elevated defensive position.' },
      { name: 'CT Spawn', area: 'ct', description: 'CT starting area. Central position for rotations.' },
      { name: 'B Site', area: 'ct', description: 'Second bombsite at temple base. Complex layout with multiple holds.' },
      { name: 'Temple', area: 'ct', description: 'Temple structure near B. Key position for B defense.' },
      { name: 'Boat', area: 'ct', description: 'Boat area near B site. Cover for site defenders.' },
      { name: 'Heaven', area: 'ct', description: 'Elevated position above B site. Strong height advantage.' },
      { name: 'Connector', area: 'ct', description: 'Passage connecting A and B areas for CT rotations.' },
      { name: 'T Spawn', area: 't', description: 'T starting area with routes to both sites.' },
      { name: 'Canal', area: 't', description: 'Water canal area. Alternative route toward B site.' },
      { name: 'Bridge', area: 't', description: 'Bridge structure in T area. Elevated crossing position.' },
      { name: 'Alley', area: 't', description: 'Narrow alley toward A site. Primary A approach path.' },
      { name: 'Water', area: 't', description: 'Water feature area. Unique terrain near B approach.' },
      { name: 'Tunnel', area: 't', description: 'Tunnel toward B site. Underground approach route.' },
      { name: 'Mid', area: 'mid', description: 'Central area connecting paths to both sites.' },
      { name: 'Street', area: 'mid', description: 'Street area in mid. Open space for mid control fights.' },
      { name: 'Pillar', area: 'mid', description: 'Pillar structures providing cover in mid area.' },
    ],
    tips: [
      'Master vertical play. Anubis features multiple levels that create unique combat scenarios.',
      'Communication is essential. Complex layout requires precise callouts.',
      'Utility defines rounds. Smokes and flashes control information and enable site takes.',
      'Patience pays off. Slow executes often work better than rushed attacks.',
      'Learn connector timings. CT rotations through connector are predictable and punishable.',
    ],
    tags: ['Complex', 'Vertical', 'Utility Heavy', 'Active Duty'],
    strategies: [
      { title: 'A Main Push', side: 't', description: 'Coordinate through main with full utility. Smoke palace and ruins for safe entry.' },
      { title: 'B Canal Execute', side: 't', description: 'Take canal control, push B through water and tunnel with molotovs for heaven.' },
      { title: 'Mid Split', side: 't', description: 'Win mid control then split to weaker site based on CT positions.' },
      { title: 'Temple Anchor', side: 'ct', description: 'Play one player heaven, one temple. Use utility to delay pushes.' },
    ],
  },
  {
    slug: 'ancient', name: 'Ancient',
    description: 'An interconnected map with Mayan temple ruins and lush vegetation. Ancient rewards map control, utility efficiency, and understanding rotation timings for smart strategic team play.',
    callouts: [
      { name: 'A Site', area: 'ct', description: 'First bombsite in the temple area. Multiple entry points require wide defense.' },
      { name: 'A Main', area: 'ct', description: 'Main corridor to A site. Primary defensive hold position.' },
      { name: 'Donut', area: 'ct', description: 'Circular structure near A site. Key crossfire position.' },
      { name: 'Elbow', area: 'ct', description: 'Elbow turn near A site. Critical angle for defenders.' },
      { name: 'CT Spawn', area: 'ct', description: 'CT starting area. Central rotation position.' },
      { name: 'B Site', area: 'ct', description: 'Second bombsite in lower area. Natural chokepoint defense.' },
      { name: 'B Main', area: 'ct', description: 'Main approach to B site. Primary B defense position.' },
      { name: 'Ramp', area: 'ct', description: 'Ramp area near B site. Elevation for defense.' },
      { name: 'Cave', area: 'ct', description: 'Cave passage connecting CT to B area. Rotation path.' },
      { name: 'Cubby', area: 'ct', description: 'Small cubby near sites for sneaky defensive positions.' },
      { name: 'T Spawn', area: 't', description: 'T starting area with paths to both sites.' },
      { name: 'Mid', area: 't', description: 'Central area. Crucial for map control.' },
      { name: 'Alley', area: 't', description: 'Alley from T spawn toward A. Primary A approach.' },
      { name: 'Jungle', area: 't', description: 'Vegetation area near mid. Cover during mid fights.' },
      { name: 'Water', area: 't', description: 'Water channel area. Alternative route.' },
      { name: 'Side Path', area: 't', description: 'Side path toward B. Alternative B approach.' },
      { name: 'Mid Control', area: 'mid', description: 'Central contested area. Winning mid opens options.' },
      { name: 'Temple', area: 'mid', description: 'Temple structure in mid. Landmark and cover.' },
    ],
    tips: [
      'Control mid early. Winning mid on Ancient opens significant site flexibility.',
      'Cave rotations are predictable. Punish slow CT rotates through cave.',
      'Utility coordination is essential. Stacked executes work best on Ancient.',
      'Learn donut smokes. Controlling donut area is key to A site attacks.',
      'Play patient defaults. Information gathering before committing wins rounds.',
    ],
    tags: ['Interconnected', 'Map Control', 'Rotations', 'Active Duty'],
    strategies: [
      { title: 'A Main Execute', side: 't', description: 'Push A main with smokes for donut and elbow. Flash site for entry.' },
      { title: 'B Ramp Stack', side: 't', description: 'Stack B main with utility. Molly ramp and smoke cave for safe take.' },
      { title: 'Mid Split', side: 't', description: 'Take mid control, rotate to whichever site shows weakness.' },
      { title: 'Cave Hold', side: 'ct', description: 'Aggressive cave position for info. Fall back on utility.' },
    ],
  },
  {
    slug: 'nuke', name: 'Nuke',
    description: 'A vertical map with upper and lower bombsites inside a nuclear facility. Heavily CT-sided, Nuke requires excellent T-side coordination and utility mastery to break through layered CT defenses.',
    callouts: [
      { name: 'A Site (Upper)', area: 'ct', description: 'Upper bombsite. Multiple angles from heaven, hut, and main.' },
      { name: 'Heaven', area: 'ct', description: 'Elevated catwalk above A site. Dominant defensive position.' },
      { name: 'Hut', area: 'ct', description: 'Small hut structure on A site. Cover position near plant zones.' },
      { name: 'Main', area: 'ct', description: 'Main entrance to A site. Primary approach from lobby.' },
      { name: 'CT Red', area: 'ct', description: 'Red container area near CT spawn. Rotation cover.' },
      { name: 'CT Spawn', area: 'ct', description: 'CT starting area between sites. Quick rotation hub.' },
      { name: 'B Site (Lower)', area: 'ct', description: 'Lower bombsite in basement. Tight angles and limited access.' },
      { name: 'Dark', area: 'ct', description: 'Dark area in B site basement. Sneaky defensive position.' },
      { name: 'Vents', area: 'ct', description: 'Ventilation shafts connecting upper and lower. Unique vertical route.' },
      { name: 'Decon', area: 'ct', description: 'Decontamination room near B. Tight corridor defense.' },
      { name: 'T Spawn (Yard)', area: 't', description: 'T starting area in the yard. Open area with routes inside.' },
      { name: 'Lobby', area: 't', description: 'Main lobby entrance. Primary route to A site.' },
      { name: 'Ramp', area: 't', description: 'Ramp from outside to lower B. Key B approach route.' },
      { name: 'Secret', area: 't', description: 'Secret passage near ramp. Alternative B approach.' },
      { name: 'Silo', area: 't', description: 'Silo structure outside. Landmark for outside plays.' },
      { name: 'Outside', area: 't', description: 'Exterior yard area. Outside control is T-side priority.' },
      { name: 'Garage', area: 'mid', description: 'Garage area connecting outside to inside. Key chokepoint.' },
      { name: 'Radio', area: 'mid', description: 'Radio room between areas. Information position.' },
      { name: 'Trophy', area: 'mid', description: 'Trophy room connecting areas. Rotation path.' },
    ],
    tips: [
      'Nuke is very CT-sided. T-side needs perfect utility and coordination to win rounds.',
      'Control outside. Yard control is essential for any T-side strategy on Nuke.',
      'Learn vent plays. Vents connect upper and lower, enabling surprise rotations.',
      'Practice ramp smokes. Ramp control is crucial for lower B takes.',
      'Use sound wisely. The vertical layout makes sound information very important.',
    ],
    tags: ['Vertical', 'CT-Sided', 'Technical', 'Active Duty'],
    strategies: [
      { title: 'A Lobby Rush', side: 't', description: 'Fast lobby push with flashes. Smoke heaven, molly hut. Overwhelm A site.' },
      { title: 'Ramp B Execute', side: 't', description: 'Take outside control, push ramp to lower B. Smoke and molly key positions.' },
      { title: 'Vent Fake', side: 't', description: 'Show presence at A through lobby while players push ramp to B through vents.' },
      { title: 'Heaven Anchor', side: 'ct', description: 'Play aggressive heaven with AWP. Fall back on utility when pushed.' },
    ],
  },
  {
    slug: 'overpass', name: 'Overpass',
    description: 'A complex multi-level map with creative utility usage and diverse playstyles. Overpass rewards map control and information gathering with relatively balanced sides and deep strategic options.',
    callouts: [
      { name: 'A Site', area: 'ct', description: 'Bombsite A on top of the overpass structure with truck, bank, and stairs positions.' },
      { name: 'Bank', area: 'ct', description: 'Building on A site providing strong holding angles and cover.' },
      { name: 'Truck', area: 'ct', description: 'Truck on A site used for boost positions and crossfires.' },
      { name: 'Van', area: 'ct', description: 'Van near A site providing cover for defenders.' },
      { name: 'Heaven (B)', area: 'ct', description: 'Elevated position above B site. One of the strongest CT positions on the map.' },
      { name: 'B Site', area: 'ct', description: 'Lower bombsite in the canal area with water, pillar, and construction.' },
      { name: 'CT Spawn', area: 'ct', description: 'CT starting area with quick access to connector and both sites.' },
      { name: 'Construction', area: 'ct', description: 'Construction area near B site used for rotations and holds.' },
      { name: 'Pillar', area: 'ct', description: 'Pillar position on B site for afterplant cover.' },
      { name: 'Long A', area: 't', description: 'Long approach to A site from T spawn. Primary A attack route.' },
      { name: 'Short A (Toilets)', area: 't', description: 'Short path to A through the bathroom area.' },
      { name: 'Monster', area: 't', description: 'Underground tunnel from T spawn toward B site. Key B approach.' },
      { name: 'Playground', area: 't', description: 'Open area near T spawn used for early aggression and staging.' },
      { name: 'T Spawn', area: 't', description: 'Terrorist starting area. Routes lead to long A, short A, and monster.' },
      { name: 'Connector', area: 'mid', description: 'Connector between A site and B site. Critical rotation path.' },
      { name: 'Fountain', area: 'mid', description: 'Fountain area in mid connector region.' },
      { name: 'Water/Canal', area: 'mid', description: 'Water canal area leading to B site. Used for sneaky approaches.' },
      { name: 'Party', area: 'mid', description: 'Area near A site connector. Contested for mid control.' },
    ],
    tips: [
      'Monster control is crucial for B site access. Use utility to clear it safely.',
      'Long A and short A split is very effective when coordinated with utility.',
      'B site executes need heaven smoke, pillar molotov, and coordinated flashes.',
      'Connector control enables fast CT rotations — contest it early.',
      'Use the multiple levels to your advantage. Boost spots can catch opponents off guard.',
    ],
    tags: ['Complex', 'Multi-Level', 'Balanced', 'Active Duty'],
    strategies: [
      { title: 'A Split (Long + Short)', side: 't', description: 'Split A with players from long and short simultaneously. Smoke bank, flash over, take site.' },
      { title: 'B Canal Execute', side: 't', description: 'Push through monster and canal. Smoke heaven, molly pillar, flash in and take site together.' },
      { title: 'Default Mid Control', side: 't', description: 'Take connector/fountain control early. Use it to split to either site based on CT positions.' },
      { title: 'Aggressive Monster', side: 'ct', description: 'Push monster early with utility for information. Fall back to heaven if overwhelmed.' },
      { title: 'A Site Crossfire', side: 'ct', description: 'Set up crossfires on A site between bank and truck. Molotov long to delay.' },
    ],
  },
  {
    slug: 'vertigo', name: 'Vertigo',
    description: 'A unique rooftop map set on a skyscraper under construction. Vertigo features dramatic height differences with close-quarters combat, offering a completely different CS2 experience from traditional maps.',
    callouts: [
      { name: 'A Site', area: 'ct', description: 'Upper A bombsite on the rooftop. Open area with limited cover.' },
      { name: 'A Ramp', area: 'ct', description: 'Ramp leading up to A site. Primary A defense position.' },
      { name: 'Elevator', area: 'ct', description: 'Elevator shaft area. Alternative route between levels.' },
      { name: 'Scaffolding', area: 'ct', description: 'Scaffolding structure near A. Height advantage position.' },
      { name: 'CT Spawn', area: 'ct', description: 'CT starting area. Quick access to both sites.' },
      { name: 'B Site', area: 'ct', description: 'Lower B bombsite. Enclosed area with tight angles.' },
      { name: 'B Stairs', area: 'ct', description: 'Stairs leading to B site. Key defensive chokepoint.' },
      { name: 'B Back', area: 'ct', description: 'Back of B site. Afterplant and defense position.' },
      { name: 'Heaven B', area: 'ct', description: 'Elevated position above B site. Height advantage.' },
      { name: 'Headshot', area: 'ct', description: 'Headshot angle position on B. Tight peek position.' },
      { name: 'T Spawn', area: 't', description: 'T starting area. Routes split to A and B.' },
      { name: 'T Mid', area: 't', description: 'T mid area. Central position for both site approaches.' },
      { name: 'A Short', area: 't', description: 'Short path to A site. Quick but exposed route.' },
      { name: 'B Tunnels', area: 't', description: 'Tunnel approach to B site. Primary B attack route.' },
      { name: 'Ladder', area: 't', description: 'Ladder connecting levels. Vertical movement route.' },
      { name: 'Sandbags', area: 't', description: 'Sandbag cover near T mid. Staging position.' },
      { name: 'Mid', area: 'mid', description: 'Central area. Contested for early round control.' },
      { name: 'Window', area: 'mid', description: 'Window area overlooking mid. Info gathering spot.' },
    ],
    tips: [
      'Watch for fall damage. Vertigo has deadly drops that punish careless movement.',
      'Close-quarters combat dominates. Shotguns and SMGs are viable on force buys.',
      'B site is claustrophobic. Use utility to clear corners before pushing.',
      'A ramp is the key chokepoint. Controlling ramp dictates A site access.',
      'Listen carefully. Sound cues are crucial due to the vertical layout.',
    ],
    tags: ['Unique', 'Close Quarters', 'Vertical', 'Active Duty'],
    strategies: [
      { title: 'A Ramp Rush', side: 't', description: 'Flash and push A ramp with numbers. Smoke scaffolding, take site fast.' },
      { title: 'B Tunnels Execute', side: 't', description: 'Stack B tunnels, molly headshot and stairs. Push together.' },
      { title: 'Mid to A Split', side: 't', description: 'Take mid control, split A from ramp and elevator.' },
      { title: 'B Stairs Hold', side: 'ct', description: 'Play aggressive B stairs with crossfire from heaven. Molly tunnel.' },
    ],
  },
];

export function getMapBySlug(slug: string): MapCalloutData | undefined {
  return MAP_CALLOUTS.find(m => m.slug === slug);
}
