// All CS2 competitive ranks data
export const allRanks = [
  {
    slug: 'silver-1', rank: 'Silver 1', abbr: 'S1', color: '#C0C0C0', percentage: 5, tier: 'Silver',
    premierRange: '0 – 2,999', percentile: 'Bottom 5%',
    description: 'Silver 1 is the entry-level rank in CS2, representing players who are brand new to the game or still learning the very basics. At this rank, players are discovering mechanics like movement, aiming, buying weapons, and basic map layouts.',
    tips: [
      'Focus on learning crosshair placement — keep your crosshair at head height',
      'Learn the buy menu and basic economy (save when you can\'t afford rifles)',
      'Practice moving and shooting separately — stop before shooting for accuracy',
      'Learn callouts for at least one map (Dust 2 or Mirage are beginner-friendly)',
      'Play Deathmatch to improve your aim before jumping into competitive',
    ],
    nextRank: 'silver-2', prevRank: null as string | null,
    avgKD: '0.60 – 0.75', avgADR: '40 – 55', avgHS: '20 – 30%',
  },
  {
    slug: 'silver-2', rank: 'Silver 2', abbr: 'S2', color: '#C0C0C0', percentage: 5, tier: 'Silver',
    premierRange: '1,000 – 3,499', percentile: '5 – 10%',
    description: 'Silver 2 players have a basic understanding of CS2 but are still developing core skills. You\'ll see improvement in aim consistency and beginning awareness of game mechanics like economy.',
    tips: [
      'Practice spray patterns for AK-47 and M4 — even controlling the first 5 bullets helps',
      'Learn when to buy and when to save (eco rounds after losing)',
      'Start using utility — even one smoke or flash per round makes a difference',
      'Communicate with your team using voice chat or the ping system',
      'Watch your own demos to identify common mistakes',
    ],
    nextRank: 'silver-3', prevRank: 'silver-1',
    avgKD: '0.65 – 0.80', avgADR: '45 – 60', avgHS: '22 – 32%',
  },
  {
    slug: 'silver-3', rank: 'Silver 3', abbr: 'S3', color: '#C0C0C0', percentage: 6, tier: 'Silver',
    premierRange: '2,000 – 4,499', percentile: '10 – 16%',
    description: 'Silver 3 players are starting to develop consistent aiming habits and understand basic strategies. Map knowledge is improving but utility usage remains limited.',
    tips: [
      'Learn 2-3 basic smoke lineups for your main map',
      'Practice counter-strafing — press the opposite direction key before shooting',
      'Start to think about positioning — don\'t stand in the open',
      'Learn to play off your teammates rather than solo pushing',
      'Focus on one map and master it before branching out',
    ],
    nextRank: 'silver-4', prevRank: 'silver-2',
    avgKD: '0.70 – 0.85', avgADR: '48 – 63', avgHS: '24 – 34%',
  },
  {
    slug: 'silver-4', rank: 'Silver 4', abbr: 'S4', color: '#C0C0C0', percentage: 6, tier: 'Silver',
    premierRange: '3,000 – 5,499', percentile: '16 – 22%',
    description: 'Silver 4 represents the upper end of Silver. Players here have decent basic skills and are ready to take the next step into Gold Nova territory with focused practice.',
    tips: [
      'Refine your sensitivity — most pros use between 400-800 eDPI',
      'Learn to jiggle-peek angles to gather information safely',
      'Practice pre-aiming common positions when entering sites',
      'Start learning economy management for the whole team, not just yourself',
      'Use grenades more deliberately — flash for entries, smoke chokepoints',
    ],
    nextRank: 'silver-elite', prevRank: 'silver-3',
    avgKD: '0.75 – 0.90', avgADR: '52 – 67', avgHS: '26 – 36%',
  },
  {
    slug: 'silver-elite', rank: 'Silver Elite', abbr: 'SE', color: '#D3D3D3', percentage: 7, tier: 'Silver',
    premierRange: '4,000 – 6,499', percentile: '22 – 29%',
    description: 'Silver Elite players have solid foundational skills and are starting to develop game sense. Aim is becoming more consistent and basic utility usage is part of the toolkit.',
    tips: [
      'Learn common pre-fire positions on your main maps',
      'Start thinking about rotations and reading the opponent\'s strategy',
      'Practice burst firing at medium range, tap firing at long range',
      'Coordinate utility with teammates for executes',
      'Review pro player demos to understand positioning',
    ],
    nextRank: 'silver-elite-master', prevRank: 'silver-4',
    avgKD: '0.80 – 0.95', avgADR: '55 – 70', avgHS: '28 – 38%',
  },
  {
    slug: 'silver-elite-master', rank: 'Silver Elite Master', abbr: 'SEM', color: '#D3D3D3', percentage: 8, tier: 'Silver',
    premierRange: '5,000 – 7,499', percentile: '29 – 37%',
    description: 'SEM is the highest Silver rank and the gateway to Gold Nova. Players here have competent aim and basic game understanding but need to refine decision-making and utility usage to rank up.',
    tips: [
      'Master at least 3-4 smoke lineups per map side',
      'Learn when to play aggressive vs passive based on round context',
      'Start tracking your opponents\' economy to predict their buys',
      'Practice aim routines daily — 15 minutes of Deathmatch before competitive',
      'Focus on trading kills — always be ready to refrag for teammates',
    ],
    nextRank: 'gold-nova-1', prevRank: 'silver-elite',
    avgKD: '0.85 – 1.00', avgADR: '58 – 73', avgHS: '30 – 40%',
  },
  {
    slug: 'gold-nova-1', rank: 'Gold Nova 1', abbr: 'GN1', color: '#FFD700', percentage: 10, tier: 'Gold Nova',
    premierRange: '6,500 – 9,499', percentile: '37 – 47%',
    description: 'Gold Nova 1 marks the transition from Silver to the Gold ranks. Players here have competent aim, use utility regularly, and understand basic team strategies. This is often considered the "average" starting point.',
    tips: [
      'Learn to anchor a bombsite on CT side — hold angles and play for retakes',
      'Develop your movement skills — smooth counter-strafes and accurate peeking',
      'Practice 1v1 clutch situations — know when to save vs when to fight',
      'Start understanding timings — when rushes arrive, when rotations happen',
      'Use the radar effectively to track teammates and gather information',
    ],
    nextRank: 'gold-nova-2', prevRank: 'silver-elite-master',
    avgKD: '0.90 – 1.05', avgADR: '62 – 77', avgHS: '32 – 42%',
  },
  {
    slug: 'gold-nova-2', rank: 'Gold Nova 2', abbr: 'GN2', color: '#FFD700', percentage: 11, tier: 'Gold Nova',
    premierRange: '7,500 – 10,999', percentile: '47 – 58%',
    description: 'Gold Nova 2 is the most populated rank in CS2. Players here represent the true average skill level with competent mechanics and developing game sense.',
    tips: [
      'Work on your crosshair placement — it should be at headshot level at all times',
      'Learn to read minimap information quickly and make rotation calls',
      'Practice spray transfers between multiple targets',
      'Start learning off-angles — positions enemies don\'t expect',
      'Focus on consistency rather than flashy plays',
    ],
    nextRank: 'gold-nova-3', prevRank: 'gold-nova-1',
    avgKD: '0.95 – 1.08', avgADR: '65 – 80', avgHS: '34 – 44%',
  },
  {
    slug: 'gold-nova-3', rank: 'Gold Nova 3', abbr: 'GN3', color: '#FFD700', percentage: 10, tier: 'Gold Nova',
    premierRange: '9,000 – 12,499', percentile: '58 – 68%',
    description: 'Gold Nova 3 players are above average with solid aim fundamentals and good map knowledge. Breaking through to Master Guardian requires refining game sense and decision-making.',
    tips: [
      'Master pop-flashes — learn to flash over walls and around corners',
      'Start thinking about your crosshair placement before engagements',
      'Learn to play for information without overcommitting',
      'Develop default strategies on T-side to gather info before executing',
      'Work on AWP positioning and quick-scoping if you play the AWP role',
    ],
    nextRank: 'gold-nova-master', prevRank: 'gold-nova-2',
    avgKD: '0.98 – 1.12', avgADR: '68 – 83', avgHS: '36 – 46%',
  },
  {
    slug: 'gold-nova-master', rank: 'Gold Nova Master', abbr: 'GNM', color: '#FFA500', percentage: 9, tier: 'Gold Nova',
    premierRange: '10,500 – 13,999', percentile: '68 – 77%',
    description: 'Gold Nova Master is the final Gold rank and a stepping stone to MG. Players here have good aim, decent utility usage, and are developing advanced game sense.',
    tips: [
      'Focus on consistency — play your default style and avoid overpeaking',
      'Learn to control the tempo of rounds as an IGL or caller',
      'Practice retake scenarios — how to approach sites with fewer players',
      'Work on your pistol round performance — pistol rounds often decide halves',
      'Understand force-buy timings and when to invest in SMGs vs rifles',
    ],
    nextRank: 'master-guardian-1', prevRank: 'gold-nova-3',
    avgKD: '1.00 – 1.15', avgADR: '70 – 85', avgHS: '38 – 48%',
  },
  {
    slug: 'master-guardian-1', rank: 'Master Guardian 1', abbr: 'MG1', color: '#4169E1', percentage: 8, tier: 'Master Guardian',
    premierRange: '12,000 – 15,999', percentile: '77 – 85%',
    description: 'MG1 is where CS2 starts getting serious. Players have strong aim, good utility usage, and developing tactical awareness. Games are noticeably more structured than Gold Nova.',
    tips: [
      'Perfect your spray control for AK-47, M4, and your secondary weapon',
      'Learn to call strats and coordinate executes with your team',
      'Develop a deep understanding of at least 3 maps in the competitive pool',
      'Practice shoulder peeking to bait out AWP shots',
      'Start analyzing your demos to find recurring mistakes in positioning',
    ],
    nextRank: 'master-guardian-2', prevRank: 'gold-nova-master',
    avgKD: '1.02 – 1.18', avgADR: '73 – 88', avgHS: '40 – 50%',
  },
  {
    slug: 'master-guardian-2', rank: 'Master Guardian 2', abbr: 'MG2', color: '#4169E1', percentage: 6, tier: 'Master Guardian',
    premierRange: '13,500 – 17,499', percentile: '85 – 91%',
    description: 'MG2 players have refined skills across all core mechanics. Games are competitive, and players who reach this rank have put significant time into improving.',
    tips: [
      'Focus on team play — trade kills, flash for teammates, play for the team',
      'Learn advanced smoke lineups including one-ways',
      'Develop a consistent warm-up routine before competitive',
      'Study professional matches to understand round-by-round decision making',
      'Work on your mental game — staying calm under pressure wins rounds',
    ],
    nextRank: 'master-guardian-elite', prevRank: 'master-guardian-1',
    avgKD: '1.05 – 1.20', avgADR: '75 – 90', avgHS: '42 – 52%',
  },
  {
    slug: 'master-guardian-elite', rank: 'Master Guardian Elite', abbr: 'MGE', color: '#1E90FF', percentage: 4, tier: 'Master Guardian',
    premierRange: '15,000 – 19,499', percentile: '91 – 95%',
    description: 'MGE is the top of Master Guardian and gateway to the elite ranks. Players here have excellent fundamentals and are starting to develop the game sense that separates good players from great ones.',
    tips: [
      'Master mid-round decision making — read the opponent\'s setup and adapt',
      'Learn to IGL or at least contribute to mid-round calls',
      'Focus on first-bullet accuracy — the first shot matters most',
      'Practice clutch scenarios — 1vX situations are common at this level',
      'Start working on advanced movement like bunny-hopping and strafing',
    ],
    nextRank: 'distinguished-master-guardian', prevRank: 'master-guardian-2',
    avgKD: '1.08 – 1.22', avgADR: '78 – 92', avgHS: '44 – 54%',
  },
  {
    slug: 'distinguished-master-guardian', rank: 'Distinguished Master Guardian', abbr: 'DMG', color: '#20B2AA', percentage: 3, tier: 'Distinguished',
    premierRange: '17,500 – 21,999', percentile: '95 – 98%',
    description: 'DMG is a prestigious rank that puts you in the top 5% of players. At this level, players have excellent aim, strong game sense, and consistent tactical play.',
    tips: [
      'Perfect your positioning — every angle should give you an advantage',
      'Learn to play multiple roles so you can adapt to team needs',
      'Work on anti-strat play — predicting and countering opponent strategies',
      'Focus on your utility efficiency — never waste a grenade',
      'Develop communication skills to lead or support your team effectively',
    ],
    nextRank: 'legendary-eagle', prevRank: 'master-guardian-elite',
    avgKD: '1.10 – 1.25', avgADR: '80 – 95', avgHS: '46 – 56%',
  },
  {
    slug: 'legendary-eagle', rank: 'Legendary Eagle', abbr: 'LE', color: '#008B8B', percentage: 2, tier: 'Legendary',
    premierRange: '20,000 – 24,999', percentile: '98 – 99%',
    description: 'Legendary Eagle players are in the top 2% of all CS2 players. Mechanical skill is extremely refined, and game sense approaches a near-professional level.',
    tips: [
      'Focus on team synergy — play with a consistent group for best results',
      'Perfect your utility usage — every nade should serve a specific purpose',
      'Work on reading the opponents within the first 30 seconds of a round',
      'Practice under pressure — play FACEIT or ESEA for higher-stakes matches',
      'Study your opponent\'s tendencies and adapt mid-game',
    ],
    nextRank: 'legendary-eagle-master', prevRank: 'distinguished-master-guardian',
    avgKD: '1.15 – 1.30', avgADR: '82 – 97', avgHS: '48 – 58%',
  },
  {
    slug: 'legendary-eagle-master', rank: 'Legendary Eagle Master', abbr: 'LEM', color: '#00CED1', percentage: 1.5, tier: 'Legendary',
    premierRange: '22,500 – 27,499', percentile: '99 – 99.5%',
    description: 'LEM puts you in the top 1.5% of players globally. At this level, every game is highly competitive with skilled opponents. Small differences in decision-making separate wins from losses.',
    tips: [
      'Focus on micro-adjustments — small improvements compound at this level',
      'Master every aspect of economy management for your team',
      'Work on your composure in high-pressure situations',
      'Study professional meta and adapt current strategies to your playstyle',
      'Develop leadership skills to guide your team through difficult rounds',
    ],
    nextRank: 'supreme-master-first-class', prevRank: 'legendary-eagle',
    avgKD: '1.18 – 1.35', avgADR: '85 – 100', avgHS: '50 – 60%',
  },
  {
    slug: 'supreme-master-first-class', rank: 'Supreme Master First Class', abbr: 'SMFC', color: '#FF4500', percentage: 0.7, tier: 'Supreme',
    premierRange: '25,000 – 29,999', percentile: '99.5 – 99.7%',
    description: 'SMFC is the second-highest competitive rank. Players here operate at a near-professional level with exceptional aim, game sense, and tactical understanding.',
    tips: [
      'Every round should have a plan — no more "just go and aim"',
      'Master the art of information gathering without dying',
      'Work on your impact frags — make kills that change the round outcome',
      'Practice playing off of utility — capitalize on every flash and smoke',
      'Consider competing in amateur tournaments or leagues',
    ],
    nextRank: 'global-elite', prevRank: 'legendary-eagle-master',
    avgKD: '1.20 – 1.40', avgADR: '88 – 105', avgHS: '52 – 62%',
  },
  {
    slug: 'global-elite', rank: 'Global Elite', abbr: 'GE', color: '#FFD700', percentage: 0.3, tier: 'Global Elite',
    premierRange: '30,000+', percentile: 'Top 0.3%',
    description: 'Global Elite is the highest rank in CS2 competitive matchmaking. Only 0.3% of the player base reaches this level. These are players with professional-level mechanics, game sense, and tactical understanding.',
    tips: [
      'Continue grinding FACEIT/ESEA for competitive improvement beyond matchmaking',
      'Consider coaching or creating content to share your knowledge',
      'Focus on team-level strategies and coordination',
      'Study top-level professional demos for cutting-edge meta',
      'Maintain your skills with consistent practice and competitive play',
    ],
    nextRank: null as string | null, prevRank: 'supreme-master-first-class',
    avgKD: '1.25 – 1.50+', avgADR: '90 – 110+', avgHS: '55 – 65%+',
  },
];
